
MESSAGE(STATUS "IHADEBUGLIB Library")

IF (NESTED_BUILD)
  SET(IHADEBUGLIB_LIBRARIES ihaDebugLib)
ELSE (NESTED_BUILD)
  FIND_LIBRARY(IHADEBUGLIB_LIBRARIES ihaDebugLib ${IHADEBUGLIB_DIR})
ENDIF (NESTED_BUILD)

SET(IHADEBUGLIB_INCLUDE_DIRS ${IHADEBUGLIB_DIR}/include)

