
MESSAGE(STATUS "SIMIO Library")

SET(SIMIO_INCLUDE_DIRS ${SIMIO_DIR})

IF (NESTED_BUILD)
  SET(SIMIO_LIBRARIES simio)
ELSE (NESTED_BUILD)
  FIND_LIBRARY(SIMIO_LIBRARIES simio ${SIMIO_DIR})
ENDIF (NESTED_BUILD)

IF (UNIX)
  SET(SIMIO_LIBRARIES ncurses ${SIMIO_LIBRARIES})
ENDIF (UNIX)

