
MESSAGE(STATUS "EGOSPHERELIB Library")

IF (NESTED_BUILD)
  SET(EGOSPHERELIB_LIBRARIES egoSphereLib)
ELSE (NESTED_BUILD)
  FIND_LIBRARY(EGOSPHERELIB_LIBRARIES egoSphereLib ${EGOSPHERELIB_DIR})
ENDIF (NESTED_BUILD)

SET(EGOSPHERELIB_INCLUDE_DIRS ${EGOSPHERELIB_DIR}/include)

