#!/bin/bash

echo $2
testo="$1"
espeak -v it -s 150 -p 110 "$testo" &
sp_pid=$!

WAIT_DT=1
WAIT_TIME=$2

echo "set mou sur" | yarp rpc /icub/face/emotions/in

expr="sur"

for((T=WAIT_DT;T<=WAIT_TIME;T+=WAIT_DT));
do
    progress=$T/$WAIT_TIME
	#echo "$expr"
	case "$expr" in
		hap)
			echo "set mou hap" | yarp rpc /icub/face/emotions/in
			expr="sur"
			;;
		sur)
			echo "set mou sur" | yarp rpc /icub/face/emotions/in
			expr="hap"
			;;
	esac

   sleep 0.3
done

#echo "set mou hap" | yarp rpc /icub/face/emotions/in

#for((T=WAIT_DT;T<=WAIT_TIME;T+=WAIT_DT));
#do
#    progress=$T/$WAIT_TIME
#	echo "$expr"
#	case "$expr" in
#		hap)
#			echo "set mou hap" | yarp rpc /icub/face/emotions/in
#			expr="sur"
#			;;
#		sur)
#			echo "set mou sur" | yarp rpc /icub/face/emotions/in
#			expr="hap"
#			;;
#	esac
#
#   sleep 0.3
#done

echo "set mou hap" | yarp rpc /icub/face/emotions/in

