MESSAGE(STATUS "IKTest Library")

IF (NESTED_BUILD)
  SET(IKTest_LIBRARIES IKTest)
ELSE (NESTED_BUILD)
  FIND_LIBRARY(IKTest_LIBRARIES IKTest ${IKTest_DIR}/lib)
ENDIF (NESTED_BUILD)

SET(IKTest_INCLUDE_DIR ${IKTest_DIR}/include)

