
MESSAGE(STATUS "IHADEBUGLIB Library")

IF (NESTED_BUILD)
  SET(IHADEBUGLIB_LIBRARIES ihaNewDebugLib)
ELSE (NESTED_BUILD)
  FIND_LIBRARY(IHADEBUGLIB_LIBRARIES ihaNewDebugLib ${IHADEBUGLIB_DIR})
ENDIF (NESTED_BUILD)

SET(IHADEBUGLIB_INCLUDE_DIRS ${IHADEBUGLIB_DIR}/include)

