
IF(NOT IKIN_FOUND)

    MESSAGE(STATUS "Using IKINConfig.cmake")
    
    SET(LIB_DIR ${IKIN_DIR})
    
    SET(ADD_IPOPT FALSE CACHE BOOL "Dou you want to add IPOPT library?")
    IF(ADD_IPOPT)
       FIND_PACKAGE(IPOPT)
       IF(NOT IPOPT_FOUND)
          MESSAGE(STATUS "IPOPT not found! Keep on building...")
       ENDIF(NOT IPOPT_FOUND)
    ELSE(ADD_IPOPT)
       SET(IPOPT_INC_DIRS "")
       SET(IPOPT_LIB "")
       SET(IPOPT_LIB_R "")
       SET(IPOPT_LIB_D "")
    ENDIF(ADD_IPOPT)
    
    SET(IKIN_INCLUDE_DIRS ${LIB_DIR}/include ${IPOPT_INC_DIRS})
    
    
    IF(NESTED_BUILD)

      SET(IKIN_LIBRARIES iKin)

      IF(IPOPT_FOUND)
        SET(IKIN_LIBRARIES ${IKIN_LIBRARIES} ${IPOPT_LIB})
      ENDIF(IPOPT_FOUND)
    
    ELSE(NESTED_BUILD)
    
      FIND_LIBRARY(IKIN_LIBRARIES iKin ${ICUB_DIR}/lib ${LIB_DIR})  
    
      IF(NOT IKIN_LIBRARIES)
    
        FIND_LIBRARY(IKIN_LIBRARIES_RELEASE iKin
    		         ${ICUB_DIR}/lib/Release ${LIB_DIR}/Release NO_DEFAULT_PATH)
        FIND_LIBRARY(IKIN_LIBRARIES_DEBUG iKind
    		         ${ICUB_DIR}/lib/Debug ${LIB_DIR}/Debug NO_DEFAULT_PATH)
    
        IF(IKIN_LIBRARIES_RELEASE AND NOT IKIN_LIBRARIES_DEBUG)
           SET(IKIN_LIBRARIES_RELEASE ${IKIN_LIBRARIES_RELEASE} ${IPOPT_LIB_R})
           SET(IKIN_LIBRARIES ${IKIN_LIBRARIES_RELEASE} CACHE PATH "release version of library" FORCE)
        ENDIF(IKIN_LIBRARIES_RELEASE AND NOT IKIN_LIBRARIES_DEBUG)
    
        IF(IKIN_LIBRARIES_DEBUG AND NOT IKIN_LIBRARIES_RELEASE)
           SET(IKIN_LIBRARIES_DEBUG ${IKIN_LIBRARIES_DEBUG} ${IPOPT_LIB_D})
           SET(IKIN_LIBRARIES ${IKIN_LIBRARIES_DEBUG} CACHE PATH "debug version of library" FORCE)
        ENDIF(IKIN_LIBRARIES_DEBUG AND NOT IKIN_LIBRARIES_RELEASE)
    
        IF(IKIN_LIBRARIES_DEBUG AND IKIN_LIBRARIES_RELEASE)
           SET(IKIN_LIBRARIES_RELEASE ${IKIN_LIBRARIES_RELEASE} ${IPOPT_LIB_R})
           SET(IKIN_LIBRARIES_DEBUG ${IKIN_LIBRARIES_DEBUG} ${IPOPT_LIB_D})
           SET(IKIN_LIBRARIES optimized ${IKIN_LIBRARIES_RELEASE}
    			              debug ${IKIN_LIBRARIES_DEBUG} CACHE PATH "debug and release version of library" FORCE)
        ENDIF(IKIN_LIBRARIES_DEBUG AND IKIN_LIBRARIES_RELEASE)
    
        MARK_AS_ADVANCED(IKIN_LIBRARIES_RELEASE)
        MARK_AS_ADVANCED(IKIN_LIBRARIES_DEBUG)
    
      ELSE(NOT IKIN_LIBRARIES)
    
        IF(IPOPT_FOUND)
          SET(IKIN_LIBRARIES ${IKIN_LIBRARIES} ${IPOPT_LIB})
        ENDIF(IPOPT_FOUND)
    
      ENDIF(NOT IKIN_LIBRARIES)

      # Add YARP dependencies
      FIND_PACKAGE(YARP)
      SET(IKIN_LIBRARIES ${IKIN_LIBRARIES} ${YARP_LIBRARIES})
      
      # Add CTRLLIB dependencies
      FIND_PACKAGE(CTRLLIB REQUIRED)
      SET(IKIN_INCLUDE_DIRS ${IKIN_INCLUDE_DIRS} ${CTRLLIB_INCLUDE_DIRS})
      SET(IKIN_LIBRARIES ${IKIN_LIBRARIES} ${CTRLLIB_LIBRARIES})
    
    ENDIF(NESTED_BUILD)
            
    IF(IKIN_INCLUDE_DIRS AND IKIN_LIBRARIES)
       SET(IKIN_FOUND TRUE)
    ELSE(IKIN_INCLUDE_DIRS AND IKIN_LIBRARIES)
       SET(IKIN_FOUND FALSE)
    ENDIF(IKIN_INCLUDE_DIRS AND IKIN_LIBRARIES)

ENDIF(NOT IKIN_FOUND)

