#!/bin/bash

case "$1" in
    stop)
		killall yarpdev
		;;
	start)
		yarpdev --device grabber --subdevice dragonfly --d 1 --width 320 --height 240 --video_type 1 --white_balance 0.5 0.5 --gain 0.34 --shutter 0.8 --name /icub/cam/right --DR2 --stamp &
		yarpdev --device grabber --subdevice dragonfly --d 0 --width 320 --height 240 --video_type 1 --white_balance 0.5 0.5 --gain 0.34 --shutter 0.8 --name /icub/cam/left --DR2 --stamp &
		;;

    *)
		echo "stop, start"
		;;
esac
