#!/bin/bash

appDir=${ICUB_ROBOTNAME:-default}

source ../../$appDir/scripts/config.sh
source ../../$appDir/scripts/config-nodes.sh

if [ X$1 = Xstart ] 
	then
	echo "First I'm going to check if nodes are up and running"
	../../default/scripts/checkNodes.sh $NODES_ALL
	if [ x$? = x1 ] ; then
		echo "OK"
	else
		echo "Sorry some nodes were not found"
		exit 0
	fi
fi

case "$1" in
    stop)
		./viewers stop
		./dragonfly stop
		;;
	start)

		echo "Starting dragonfly devices on $NODE_CAMERAS"
		./dragonfly start
		echo "Starting viewers on $NODE_VIEWERS"
		./viewers start
		echo "Waiting for $NAME_SOURCE_IMAGE_RIGHT"
		yarp wait $NAME_SOURCE_IMAGE_RIGHT
		echo "Waiting for $NAME_SOURCE_IMAGE_LEFT"
		yarp wait $NAME_SOURCE_IMAGE_LEFT
		
		echo "Waiting for $VIEWERS_PORT_RIGHT"
		yarp wait $VIEWERS_PORT_RIGHT
		echo "Waiting for $VIEWERS_PORT_LEFT"
		yarp wait $VIEWERS_PORT_LEFT

		echo "Connecting viewers"
		./viewers connect
		echo "done!"
		;;
	*)
		echo "stop, start"
		;;
esac
