#!/bin/bash

appDir=${ICUB_ROBOTNAME:-default}
source ../../$appDir/scripts/config.sh

# in some cases config or config-nodes define
# a different program for running the cameras 
# (icubmoddev). By default we want yarpdev.
dev=${FRAMEGRABBER_DEV:-yarpdev}

case "$1" in
    stop)
		killall $dev
		;;
	start)
		command="$dev $DRAGONFLY_CONFIG_LEFT"
		bash -c "$command &"
		command="$dev $DRAGONFLY_CONFIG_RIGHT"
		bash -c "$command &"
		;;

    *)
		echo "stop, start"
		;;
esac
