#!/bin/bash

appDir=${ICUB_ROBOTNAME:-default}

source ../../$appDir/scripts/config.sh
source ../../$appDir/scripts/config-nodes.sh

# in some cases config or config-nodes define
# a different program for running the cameras 
# (icubmoddev). By default we want yarpdev.
dev=${FRAMEGRABBER_DEV:-yarpdev}

case "$1" in
    stop)
  		yarprun --on $NODE_CAMERAS --kill $TAG_CAMERA_RIGHT
		yarprun --on $NODE_CAMERAS --kill $TAG_CAMERA_LEFT
		;;
	start)
		command="$dev $DRAGONFLY_CONFIG_LEFT"
		yarprun --on $NODE_CAMERAS --as $TAG_CAMERA_LEFT --cmd "$command"
		command="$dev $DRAGONFLY_CONFIG_RIGHT"
		yarprun --on $NODE_CAMERAS --as $TAG_CAMERA_RIGHT --cmd "$command"
		;;

    *)
		echo "stop, start"
		;;
esac
