#!/bin/bash

source ./config.sh

DRAGONFLY_CONFIG_LEFT="--device test_grabber --width 320 --height 200 --name /testgrabber1"
DRAGONFLY_CONFIG_RIGHT="--device test_grabber --width 320 --height 200 --name /testgrabber2"

case "$1" in
    stop)
		killall yarpdev
		;;
	start)
		command="yarpdev $DRAGONFLY_CONFIG_LEFT"
		bash -c "$command &"

		command="yarpdev $DRAGONFLY_CONFIG_RIGHT"
		bash -c "$command &"
		;;

    *)
		echo "stop, start"
		;;
esac
