#!/bin/bash
appDir=${ICUB_ROBOTNAME:-default}
source ../../$appDir/scripts/config.sh

case "$1" in
    stop)
		killall yarpview
		killall frameGrabberGui
		;;
	start)
		command="yarpview --name $VIEWERS_PORT_LEFT --x $VIEWERS_X_LEFT --y $VIEWERS_Y_LEFT"
		bash -c "$command &"

		command="yarpview --name $VIEWERS_PORT_RIGHT --x $VIEWERS_X_RIGHT --y $VIEWERS_Y_RIGHT"
		bash -c "$command &"

		command="frameGrabberGui $FGGUI_CONFIG_LEFT"
		bash -c "$command &"

		command="frameGrabberGui $FGGUI_CONFIG_RIGHT"
		bash -c "$command &"
		;;

	connect)
		yarp connect $NAME_SOURCE_IMAGE_LEFT $VIEWERS_PORT_LEFT $IMAGES_PROTOCOL
		yarp connect $NAME_SOURCE_IMAGE_RIGHT $VIEWERS_PORT_RIGHT $IMAGES_PROTOCOL
		yarp connect $FGGUI_NAME_RIGHT $NAME_SOURCE_IMAGE_RIGHT
		yarp connect $FGGUI_NAME_LEFT $NAME_SOURCE_IMAGE_LEFT
		;;
    *)
		echo "stop, start, connect"
		;;
esac
