#!/bin/bash

appDir=${ICUB_ROBOTNAME:-default}

source ../../$appDir/scripts/config.sh
source ../../$appDir/scripts/config-nodes.sh

VERBOSE=--verbose

case "$1" in
    stop)
		yarprun --on $NODE_VIEWERS --kill $TAG_VIEWER_RIGHT
		yarprun --on $NODE_VIEWERS --kill $TAG_VIEWER_LEFT
		yarprun --on $NODE_VIEWERS --kill $TAG_FGGUI_RIGHT
		yarprun --on $NODE_VIEWERS --kill $TAG_FGGUI_LEFT
		;;
	start)
		command="yarpview --name $VIEWERS_PORT_LEFT --x $VIEWERS_X_LEFT --y $VIEWERS_Y_LEFT"
		yarprun $VERBOSE --on $NODE_VIEWERS --as $TAG_VIEWER_LEFT --cmd "$command"	

		command="yarpview --name $VIEWERS_PORT_RIGHT --x $VIEWERS_X_RIGHT --y $VIEWERS_Y_RIGHT"
		yarprun $VERBOSE --on $NODE_VIEWERS --as $TAG_VIEWER_RIGHT --cmd "$command"

		command="frameGrabberGui $FGGUI_CONFIG_LEFT"
		yarprun $VERBOSE --on $NODE_VIEWERS --as $TAG_FGGUI_LEFT --cmd "$command"

		command="frameGrabberGui $FGGUI_CONFIG_RIGHT"
		yarprun $VERBOSE --on $NODE_VIEWERS --as $TAG_FGGUI_RIGHT --cmd "$command"
		;;

	connect)
		yarp connect $NAME_SOURCE_IMAGE_LEFT $VIEWERS_PORT_LEFT $IMAGES_PROTOCOL
		yarp connect $NAME_SOURCE_IMAGE_RIGHT $VIEWERS_PORT_RIGHT $IMAGES_PROTOCOL
		yarp connect $FGGUI_NAME_RIGHT $NAME_SOURCE_IMAGE_RIGHT
		yarp connect $FGGUI_NAME_LEFT $NAME_SOURCE_IMAGE_LEFT
		;;
    *)
		echo "stop, start, connect"
		;;
esac
