# Searches rfwr package. Assume ICUB_DIR is defined.
# Set:
# RFWR_FOUND
# RFWR_INCLUDE_DIRS
# RFWR_LIBRARIES

MESSAGE(STATUS "RFWR Library")

FIND_LIBRARY(RFWR_LIBRARIES
  NAMES  rfwr
  PATHS ${RFWR_DIR}/lib ${RFWR_DIR})

FIND_PATH(RFWR_INCLUDE_DIRS RFNet.h  ${RFWR_DIR})

IF (RFWR_INCLUDE_DIRS AND RFWR_LIBRARIES)
  SET(RFWR_FOUND TRUE)
ELSE (RFWR_INCLUDE_DIRS AND RFWR_LIBRARIES)
  SET(RFWR_FOUND FALSE)
ENDIF(RFWR_INCLUDE_DIRS AND RFWR_LIBRARIES)