#
# Standard Makefile for a Webots physics shared library
#
# Author: Olivier.Michel@cyberbotics.com
# Date:   August 30th, 2006.
#

#DOS_CONSOLE=1

ifndef WEBOTS_HOME_PATH
WEBOTS_HOME_PATH=$(WEBOTS_HOME)
endif

include $(WEBOTS_HOME_PATH)/projects/default/plugins/physics/Makefile.include
