
MESSAGE(STATUS "SALIENCELIB Library")

IF (NESTED_BUILD)
  SET(SALIENCELIB_LIBRARIES salienceLib)
ELSE (NESTED_BUILD)
  FIND_LIBRARY(SALIENCELIB_LIBRARIES salienceLib ${SALIENCELIB_DIR})
ENDIF (NESTED_BUILD)

SET(SALIENCELIB_INCLUDE_DIRS ${SALIENCELIB_DIR}/include)

