
IF(NOT CTRLLIB_FOUND)

    MESSAGE(STATUS "Using CTRLLIBConfig.cmake")
    
    SET(LIB_DIR ${CTRLLIB_DIR})
    SET(CTRLLIB_INCLUDE_DIRS ${LIB_DIR}/include)
    
    
    IF(NESTED_BUILD)
    
      IF(WIN32 AND NOT CYGWIN)
         SET(CTRLLIB_LIBRARIES optimized ctrlLib debug ctrlLibd)
         IF(MSVC)
            LINK_DIRECTORIES(${ICUB_DIR}/lib/Debug)
         ENDIF(MSVC)
      ELSE(WIN32 AND NOT CYGWIN)
         SET(CTRLLIB_LIBRARIES ctrlLib)
      ENDIF(WIN32 AND NOT CYGWIN)
    
    ELSE(NESTED_BUILD)
    
      FIND_LIBRARY(CTRLLIB_LIBRARIES ctrlLib ${ICUB_DIR}/lib ${LIB_DIR})  
    
      IF(NOT CTRLLIB_LIBRARIES)
    
        FIND_LIBRARY(CTRLLIB_LIBRARIES_RELEASE ctrlLib 
    		         ${ICUB_DIR}/lib/Release ${LIB_DIR}/Release NO_DEFAULT_PATH)
        FIND_LIBRARY(CTRLLIB_LIBRARIES_DEBUG ctrlLibd
    		         ${ICUB_DIR}/lib/Debug ${LIB_DIR}/Debug NO_DEFAULT_PATH)
    
        IF(CTRLLIB_LIBRARIES_RELEASE AND NOT CTRLLIB_LIBRARIES_DEBUG)
           SET(CTRLLIB_LIBRARIES ${CTRLLIB_LIBRARIES_RELEASE} CACHE PATH "release version of library" FORCE)
        ENDIF(CTRLLIB_LIBRARIES_RELEASE AND NOT CTRLLIB_LIBRARIES_DEBUG)
    
        IF(CTRLLIB_LIBRARIES_DEBUG AND NOT CTRLLIB_LIBRARIES_RELEASE)
           SET(CTRLLIB_LIBRARIES ${CTRLLIB_LIBRARIES_DEBUG} CACHE PATH "debug version of library" FORCE)
        ENDIF(CTRLLIB_LIBRARIES_DEBUG AND NOT CTRLLIB_LIBRARIES_RELEASE)
    
        IF(CTRLLIB_LIBRARIES_DEBUG AND CTRLLIB_LIBRARIES_RELEASE)
           SET(CTRLLIB_LIBRARIES optimized ${CTRLLIB_LIBRARIES_RELEASE}
    			                 debug ${CTRLLIB_LIBRARIES_DEBUG} CACHE PATH "debug and release version of library" FORCE)
        ENDIF(CTRLLIB_LIBRARIES_DEBUG AND CTRLLIB_LIBRARIES_RELEASE)
    
        MARK_AS_ADVANCED(CTRLLIB_LIBRARIES_RELEASE)
        MARK_AS_ADVANCED(CTRLLIB_LIBRARIES_DEBUG)
    
      ENDIF(NOT CTRLLIB_LIBRARIES)
    
    ENDIF(NESTED_BUILD)
    
    
    # Add YARP dependencies
    FIND_PACKAGE(YARP)
    SET(CTRLLIB_LIBRARIES ${CTRLLIB_LIBRARIES} ${YARP_LIBRARIES})
    
    
    IF(CTRLLIB_INCLUDE_DIRS AND CTRLLIB_LIBRARIES)
       SET(CTRLLIB_FOUND TRUE)
    ELSE(CTRLLIB_INCLUDE_DIRS AND CTRLLIB_LIBRARIES)
       SET(CTRLLIB_FOUND FALSE)
    ENDIF(CTRLLIB_INCLUDE_DIRS AND CTRLLIB_LIBRARIES)
    
ENDIF(NOT CTRLLIB_FOUND)



