# Copyright (C) 2008 RobotCub Consortium, European Commission FP6 Project IST-004370
# Author: Assif Mirza

# Machines and their paths
# See end for processor map (i.e. where processes are run)
LOCAL=local
LOCAL_APPLICATION_PATH=$ICUB_DIR/app/ihaNew
LOCAL_CONFIG_PATH=$LOCAL_APPLICATION_PATH/conf

ICUB12=icub12
ICUB12_APPLICATION_PATH=$ICUB_DIR/app/ihaNew
ICUB12_CONFIG_PATH=$ICUB12_APPLICATION_PATH/conf

#note: icub3 has portaudio installed. other machines don't
ICUB3=icub3
ICUB3_APPLICATION_PATH=$ICUB_DIR/app/ihaNew
ICUB3_CONFIG_PATH=$ICUB3_APPLICATION_PATH/conf

ICUB15=icub15
ICUB15_APPLICATION_PATH=$ICUB_DIR/app/ihaNew
ICUB15_CONFIG_PATH=$ICUB15_APPLICATION_PATH/conf

ICUB11=icub11
ICUB11_APPLICATION_PATH=$ICUB_DIR/app/ihaNew
ICUB11_CONFIG_PATH=$ICUB11_APPLICATION_PATH/conf

#BLADE5=icub3
#BLADE5_APPLICATION_PATH=$ICUB_DIR/app/ihaNew
#BLADE5_CONFIG_PATH=$BLADE5_APPLICATION_PATH/conf

#BLADE6=icub-b6
#BLADE6_APPLICATION_PATH=$ICUB_DIR/app/ihaNew
#BLADE6_CONFIG_PATH=$BLADE6_APPLICATION_PATH/conf

#ICUB3=icub3
#ICUB3_APPLICATION_PATH=$ICUB_DIR/app/ihaNew
#ICUB3_CONFIG_PATH=$ICUB3_APPLICATION_PATH/conf

# Processor Configuration Map
#
ALL_LOCAL=1
if [ $ALL_LOCAL -eq 1 ]
then
FACEDETECT_MACHINE=LOCAL
PORTAUDIO_MACHINE=LOCAL
SOUNDSERVER_MACHINE=LOCAL
DYNAMICS_MACHINE=LOCAL
CONTROLLER_MACHINE=LOCAL
DATASTORE_MACHINE=LOCAL
ACTIONSEL_MACHINE=LOCAL
SMI_INTERFACE_MACHINE=LOCAL
SFW_MACHINE=LOCAL
MONITOR_MACHINE=LOCAL
SALIENCE_MACHINE=LOCAL
MOBEYE_MACHINE=LOCAL
SELFFACEDETECT_MACHINE=LOCAL
STM_MACHINE=LOCAL
else
FACEDETECT_MACHINE=LOCAL
DYNAMICS_MACHINE=LOCAL
SMI_INTERFACE_MACHINE=LOCAL
SFW_MACHINE=LOCAL
PORTAUDIO_MACHINE=ICUB3
SOUNDSERVER_MACHINE=LOCAL
MONITOR_MACHINE=ICUB3
SALIENCE_MACHINE=LOCAL
MOBEYE_MACHINE=LOCAL
CONTROLLER_MACHINE=LOCAL
DATASTORE_MACHINE=LOCAL
ACTIONSEL_MACHINE=LOCAL
SELFFACEDETECT_MACHINE=LOCAL
STM_MACHINE=LOCAL
fi

# Window positions and sizes
SCREEN2=1280
SOUNDSERVER_GEOM=90x8+$(( $SCREEN2 + 800 ))+0
DYNAMICS_GEOM=90x16+$(( $SCREEN2 + 800 ))+160
CONTROLLER_GEOM=90x20+$(( $SCREEN2 + 800 ))+400
DATASTORE_GEOM=130x28+$(( $SCREEN2 + 0 ))+0
ACTIONSEL_GEOM=140x32+$(( $SCREEN2 + 0 ))+600 
SMI_GEOM=100x28+$(( $SCREEN2 + 0 ))+300 
STM_GEOM=100x28+$(( $SCREEN2 + 0 ))+200
LOGDIR=$LOCAL_APPLICATION_PATH/logs
