# Copyright (C) 2008 RobotCub Consortium, European Commission FP6 Project IST-004370
# Author: Assif Mirza

# Machines and their paths
# See end for processor map (i.e. where processes are run)
LOCAL=local
LOCAL_APPLICATION_PATH=$ICUB_DIR/app/iha_new
LOCAL_CONFIG_PATH=$LOCAL_APPLICATION_PATH/conf

BLADE1=icub-b1
BLADE1_APPLICATION_PATH=$ICUB_DIR/app/iha_new
BLADE1_CONFIG_PATH=$BLADE1_APPLICATION_PATH/conf

BLADE2=icub-b2
BLADE2_APPLICATION_PATH=$ICUB_DIR/app/iha_new
BLADE2_CONFIG_PATH=$BLADE2_APPLICATION_PATH/conf

BLADE3=icub-b3
BLADE3_APPLICATION_PATH=$ICUB_DIR/app/iha_new
BLADE3_CONFIG_PATH=$BLADE3_APPLICATION_PATH/conf

BLADE4=icub-b4
BLADE4_APPLICATION_PATH=$ICUB_DIR/app/iha_new
BLADE4_CONFIG_PATH=$BLADE4_APPLICATION_PATH/conf

BLADE5=icub-b5
BLADE5_APPLICATION_PATH=$ICUB_DIR/app/iha_new
BLADE5_CONFIG_PATH=$BLADE5_APPLICATION_PATH/conf

BLADE6=icub-b6
BLADE6_APPLICATION_PATH=$ICUB_DIR/app/iha_new
BLADE6_CONFIG_PATH=$BLADE6_APPLICATION_PATH/conf

ICUB3=icub3
ICUB3_APPLICATION_PATH=$ICUB_DIR/app/iha_new
ICUB3_CONFIG_PATH=$ICUB3_APPLICATION_PATH/conf

# Processor Configuration Map
#
ALL_LOCAL=1
if [ $ALL_LOCAL -eq 1 ]
then
FACEDETECT_MACHINE=LOCAL
PORTAUDIO_MACHINE=LOCAL
SOUNDSERVER_MACHINE=LOCAL
DYNAMICS_MACHINE=LOCAL
CONTROLLER_MACHINE=LOCAL
DATASTORE_MACHINE=LOCAL
ACTIONSEL_MACHINE=LOCAL
SMI_INTERFACE_MACHINE=LOCAL
SFW_MACHINE=LOCAL
MONITOR_MACHINE=LOCAL
SALIENCE_MACHINE=LOCAL
MOBEYE_MACHINE=LOCAL
SELFFACEDETECT_MACHINE=LOCAL
else
FACEDETECT_MACHINE=BLADE1
PORTAUDIO_MACHINE=ICUB3
SOUNDSERVER_MACHINE=LOCAL
DYNAMICS_MACHINE=LOCAL
CONTROLLER_MACHINE=LOCAL
DATASTORE_MACHINE=BLADE2
ACTIONSEL_MACHINE=LOCAL
SMI_INTERFACE_MACHINE=LOCAL
SFW_MACHINE=LOCAL
MONITOR_MACHINE=LOCAL
SALIENCE_MACHINE=LOCAL
MOBEYE_MACHINE=LOCAL
SELFFACEDETECT_MACHINE=LOCAL
fi

# Window positions and sizes
SCREEN2=1280
SOUNDSERVER_GEOM=90x8+$(( $SCREEN2 + 800 ))+0
DYNAMICS_GEOM=90x16+$(( $SCREEN2 + 800 ))+160
CONTROLLER_GEOM=90x20+$(( $SCREEN2 + 800 ))+400
DATASTORE_GEOM=130x28+$(( $SCREEN2 + 0 ))+0
ACTIONSEL_GEOM=140x32+$(( $SCREEN2 + 0 ))+600 
SMI_GEOM=100x28+$(( $SCREEN2 + 0 ))+300 

LOGDIR=$LOCAL_APPLICATION_PATH/logs
