
MESSAGE(STATUS "KINEMATICS Library")

IF (NESTED_BUILD)
  SET(KINEMATICS_LIBRARIES kinematics)
ELSE (NESTED_BUILD)
  FIND_LIBRARY(KINEMATICS_LIBRARIES kinematics ${KINEMATICS_DIR})
ENDIF (NESTED_BUILD)

SET(KINEMATICS_INCLUDE_DIRS ${KINEMATICS_DIR}/include)

