#include "CalibrationWriter.h"

#include <cerrno>
#include <cmath>
#include <cstdio>
#include <cstring>
#include <fstream>
#include <iomanip>
#include <sstream>

#include <opencv2/imgcodecs.hpp>
#include <opencv2/imgproc.hpp>

namespace
{

bool isFinite(const cv::Mat& matrix)
{
    return !matrix.empty() && cv::checkRange(matrix, true, nullptr);
}

bool isFinite(double value)
{
    return std::isfinite(value);
}

double matrixValue(const cv::Mat& matrix, int index)
{
    return matrix.reshape(1, 1).at<double>(0, index);
}

void writeMatrix(std::ostream& output, const std::string& name, const cv::Mat& matrix)
{
    output << name << " (";
    for (int index = 0; index < static_cast<int>(matrix.total()); ++index)
    {
        if (index != 0)
        {
            output << ' ';
        }
        output << matrixValue(matrix, index);
    }
    output << ")\n";
}

void writeCamera(std::ostream& output, const char* side, std::string projection,
                 const stereo_calib::CameraCalibrationResult& camera)
{
    output << "[CAMERA_CALIBRATION_" << side << "]\n";
    output << "projection " << projection << "\n";
    output << "drawCenterCross 0\n\n";
    output << "w " << camera.imageSize.width << "\n";
    output << "h " << camera.imageSize.height << "\n";
    output << "fx " << matrixValue(camera.K, 0) << "\n";
    output << "fy " << matrixValue(camera.K, 4) << "\n";
    output << "cx " << matrixValue(camera.K, 2) << "\n";
    output << "cy " << matrixValue(camera.K, 5) << "\n";
    if (projection == "fisheye")
    {
        output << "k1 " << matrixValue(camera.D, 0) << "\n";
        output << "k2 " << matrixValue(camera.D, 1) << "\n";
        output << "k3 " << matrixValue(camera.D, 2) << "\n";
        output << "k4 " << matrixValue(camera.D, 3) << "\n\n";
    }
    else if (projection == "pinhole")
    {
        output << "k1 " << matrixValue(camera.D, 0) << "\n";
        output << "k2 " << matrixValue(camera.D, 1) << "\n";
        output << "p1 " << matrixValue(camera.D, 2) << "\n";
        output << "p2 " << matrixValue(camera.D, 3) << "\n\n";
    }
    else
    {
        output << "# Unknown projection type '" << projection
               << "'; distortion coefficients not written.\n\n";
    }
}

std::string temporaryObservationFile(const std::string& filename)
{
    const std::size_t separator = filename.find_last_of("/\\");
    const std::size_t extension = filename.find_last_of('.');
    if (extension != std::string::npos &&
        (separator == std::string::npos || extension > separator))
    {
        return filename.substr(0, extension) + ".tmp" + filename.substr(extension);
    }
    return filename + ".tmp.yml";
}

std::string joinPath(const std::string& directory, const std::string& filename)
{
    if (directory.empty() || directory.back() == '/' || directory.back() == '\\')
    {
        return directory + filename;
    }
    return directory + '/' + filename;
}

bool isValidObservation(const stereo_calib::StereoObservation& observation)
{
    if (!observation.isValid() || !isFinite(observation.leftTimestampSeconds) ||
        !isFinite(observation.rightTimestampSeconds) ||
        !isFinite(observation.timestampDeltaSeconds))
    {
        return false;
    }
    for (std::size_t index = 0; index < observation.objectPoints.size(); ++index)
    {
        const cv::Point3f& objectPoint = observation.objectPoints[index];
        const cv::Point2f& leftPoint = observation.leftImagePoints[index];
        const cv::Point2f& rightPoint = observation.rightImagePoints[index];
        if (!isFinite(objectPoint.x) || !isFinite(objectPoint.y) || !isFinite(objectPoint.z) ||
            !isFinite(leftPoint.x) || !isFinite(leftPoint.y) ||
            !isFinite(rightPoint.x) || !isFinite(rightPoint.y))
        {
            return false;
        }
    }
    return true;
}

} // namespace

namespace stereo_calib
{

bool CalibrationWriter::write(const std::string& outputFile,
                              const CalibrationResult& result,
                              std::string& errorMessage) const
{
    errorMessage.clear();
    if (outputFile.empty())
    {
        errorMessage = "Calibration output filename is empty.";
        return false;
    }
    if (!validateResult(result, errorMessage))
    {
        return false;
    }

    const std::string temporaryFile = outputFile + ".tmp";
    std::ofstream output(temporaryFile.c_str(), std::ios::out | std::ios::trunc);
    if (!output.is_open())
    {
        errorMessage = "Could not open temporary calibration file '" + temporaryFile +
                       "': " + std::strerror(errno);
        return false;
    }

    output << std::setprecision(17);
    output << "# Generated by stereoCalib. Do not edit while calibration is running.\n";
    switch (result.mode)
    {
        case CalibrationMode::MonocularLeft:  output << "calibrationMode MonocularLeft\n\n"; break;
        case CalibrationMode::MonocularRight: output << "calibrationMode MonocularRight\n\n"; break;
        case CalibrationMode::MonocularBoth:  output << "calibrationMode MonocularBoth\n\n"; break;
        case CalibrationMode::StereoFull:     output << "calibrationMode StereoFull\n\n"; break;
    }

    const bool writesLeftCamera = result.mode != CalibrationMode::MonocularRight;
    const bool writesRightCamera = result.mode != CalibrationMode::MonocularLeft;
    const std::string projection = (result.model == CameraModel::Pinhole) ? "pinhole" : "fisheye";
    if (writesLeftCamera)
    {
        writeCamera(output, "LEFT", projection, result.leftCamera);
    }
    if (writesRightCamera)
    {
        writeCamera(output, "RIGHT", projection, result.rightCamera);
    }

    if (result.mode == CalibrationMode::StereoFull)
    {
        cv::Mat homogeneousTransform = cv::Mat::eye(4, 4, CV_64F);
        result.stereo.R.copyTo(homogeneousTransform(cv::Rect(0, 0, 3, 3)));
        result.stereo.T.reshape(1, 3).copyTo(homogeneousTransform(cv::Rect(3, 0, 1, 3)));

        output << "[STEREO_DISPARITY]\n";
        // This is deliberately left-to-right: Xright = R * Xleft + T.
        writeMatrix(output, "HN", homogeneousTransform);
        writeMatrix(output, "R", result.stereo.R);
        writeMatrix(output, "T", result.stereo.T);
    }

    output << "[CALIBRATION_QUALITY]\n";
    if (writesLeftCamera)
    {
        output << "leftRms " << result.leftCamera.rms << "\n";
    }
    if (writesRightCamera)
    {
        output << "rightRms " << result.rightCamera.rms << "\n";
    }
    if (result.mode == CalibrationMode::StereoFull)
    {
        output << "stereoRms " << result.stereo.rms << "\n";
        output << "baseline " << result.quality.baseline << "\n";
        output << "synchronizedPairs " << result.quality.synchronizedPairs << "\n";
        output << "acceptedObservations " << result.quality.acceptedObservations << "\n";
        output << "rejectedDetections " << result.quality.rejectedDetections << "\n";
        output << "meanTimestampDeltaMs " << result.quality.meanTimestampDeltaMs << "\n";
        output << "maxTimestampDeltaMs " << result.quality.maxTimestampDeltaMs << "\n";
    }

    output.flush();
    if (!output.good())
    {
        errorMessage = "Failed while writing temporary calibration file '" + temporaryFile + "'.";
        return false;
    }
    output.close();
    if (output.fail())
    {
        errorMessage = "Could not close temporary calibration file '" + temporaryFile + "'.";
        return false;
    }

    std::ifstream validation(temporaryFile.c_str());
    if (!validation.good())
    {
        errorMessage = "Could not validate temporary calibration file '" + temporaryFile + "'.";
        return false;
    }
    validation.close();
    if (std::rename(temporaryFile.c_str(), outputFile.c_str()) != 0)
    {
        errorMessage = "Could not replace calibration file '" + outputFile + "' with temporary file: " +
                       std::strerror(errno);
        return false;
    }
    return true;
}

bool CalibrationWriter::writeObservations(const std::string& outputFile,
                                          const std::vector<StereoObservation>& observations,
                                          std::string& errorMessage) const
{
    errorMessage.clear();
    if (outputFile.empty())
    {
        errorMessage = "Observation output filename is empty.";
        return false;
    }
    for (std::size_t index = 0; index < observations.size(); ++index)
    {
        if (!isValidObservation(observations[index]))
        {
            errorMessage = "Observation #" + std::to_string(index) + " is invalid.";
            return false;
        }
    }

    const std::string temporaryFile = temporaryObservationFile(outputFile);
    try
    {
        cv::FileStorage storage(temporaryFile, cv::FileStorage::WRITE);
        if (!storage.isOpened())
        {
            errorMessage = "Could not open temporary observation file '" + temporaryFile + "'.";
            return false;
        }

        storage << "observations" << "[";
        for (std::size_t index = 0; index < observations.size(); ++index)
        {
            const StereoObservation& observation = observations[index];
            storage << "{";
            storage << "index" << static_cast<int>(index);
            storage << "imageWidth" << observation.imageSize.width;
            storage << "imageHeight" << observation.imageSize.height;
            storage << "leftTimestampSeconds" << observation.leftTimestampSeconds;
            storage << "rightTimestampSeconds" << observation.rightTimestampSeconds;
            storage << "timestampDeltaSeconds" << observation.timestampDeltaSeconds;
            storage << "leftSequenceNumber" << std::to_string(observation.leftSequenceNumber);
            storage << "rightSequenceNumber" << std::to_string(observation.rightSequenceNumber);
            storage << "leftImageFilename" << observation.leftImageFilename;
            storage << "rightImageFilename" << observation.rightImageFilename;
            storage << "objectPoints" << cv::Mat(observation.objectPoints);
            storage << "leftImagePoints" << cv::Mat(observation.leftImagePoints);
            storage << "rightImagePoints" << cv::Mat(observation.rightImagePoints);
            storage << "}";
        }
        storage << "]";
        storage.release();

        cv::FileStorage validation(temporaryFile, cv::FileStorage::READ);
        const cv::FileNode serializedObservations = validation["observations"];
        if (!validation.isOpened() || serializedObservations.type() != cv::FileNode::SEQ ||
            serializedObservations.size() != observations.size())
        {
            errorMessage = "Could not validate temporary observation file '" + temporaryFile + "'.";
            return false;
        }
    }
    catch (const cv::Exception& exception)
    {
        errorMessage = std::string("Could not write observation file: ") + exception.what();
        return false;
    }
    if (std::rename(temporaryFile.c_str(), outputFile.c_str()) != 0)
    {
        errorMessage = "Could not replace observation file '" + outputFile + "' with temporary file: " +
                       std::strerror(errno);
        return false;
    }
    return true;
}

bool CalibrationWriter::writeImagePair(const std::string& outputDirectory,
                                       std::size_t observationIndex,
                                       const cv::Mat& leftImg,
                                       const cv::Mat& rightImg,
                                       std::string& leftFile,
                                       std::string& rightFile,
                                       std::string& errorMessage) const
{
    errorMessage.clear();
    leftFile.clear();
    rightFile.clear();
    if (outputDirectory.empty() || leftImg.empty() || rightImg.empty())
    {
        errorMessage = "Cannot save an image pair without an output directory and two images.";
        return false;
    }
    if (leftImg.size() != rightImg.size())
    {
        errorMessage = "Cannot save an image pair with different image sizes.";
        return false;
    }

    std::ostringstream name;
    name << std::setfill('0') << std::setw(4) << observationIndex;
    leftFile = "left_" + name.str() + ".png";
    rightFile = "right_" + name.str() + ".png";

    cv::Mat leftToWrite;
    cv::Mat rightToWrite;
    try
    {
        if (leftImg.channels() == 3)
        {
            cv::cvtColor(leftImg, leftToWrite, cv::COLOR_RGB2BGR);
        }
        else
        {
            leftToWrite = leftImg.clone();
        }
        if (rightImg.channels() == 3)
        {
            cv::cvtColor(rightImg, rightToWrite, cv::COLOR_RGB2BGR);
        }
        else
        {
            rightToWrite = rightImg.clone();
        }

        if (!cv::imwrite(joinPath(outputDirectory, leftFile), leftToWrite))
        {
            errorMessage = "Could not write left calibration image '" + joinPath(outputDirectory, leftFile) + "'.";
            return false;
        }
        if (!cv::imwrite(joinPath(outputDirectory, rightFile), rightToWrite))
        {
            errorMessage = "Could not write right calibration image '" + joinPath(outputDirectory, rightFile) + "'.";
            return false;
        }
    }
    catch (const cv::Exception& exception)
    {
        errorMessage = std::string("Could not write calibration images: ") + exception.what();
        return false;
    }
    return true;
}

bool CalibrationWriter::validateResult(const CalibrationResult& result,
                                       std::string& errorMessage) const
{
    errorMessage.clear();
    if (!result.isValid())
    {
        errorMessage = "Cannot serialize an invalid calibration result";
        return false;
    }
    return true;
}

} // namespace stereo_calib
