MESSAGE(STATUS "ATTENTIONSELECTIONLIB Library")

IF (NESTED_BUILD)
  SET(ATTENTIONSELECTIONLIB_LIBRARIES attentionSelectionLib)
ELSE (NESTED_BUILD)
  FIND_LIBRARY(ATTENTIONSELECTIONLIB_LIBRARIES attentionSelectionLib ${ATTENTIONSELECTIONLIB_DIR})
ENDIF (NESTED_BUILD)

SET(ATTENTIONSELECTIONLIB_INCLUDE_DIRS ${ATTENTIONSELECTIONLIB_DIR}/include)

