
MESSAGE(STATUS "PREDICTORS Library")

IF (NESTED_BUILD)
  SET(PREDICTORS_LIBRARIES predictors)
ELSE (NESTED_BUILD)
  FIND_LIBRARY(PREDICTORS_LIBRARIES predictors ${PREDICTORS_DIR})
ENDIF (NESTED_BUILD)

SET(PREDICTORS_INCLUDE_DIRS ${PREDICTORS_DIR}/include)

