/** ###################################################################
**     THIS BEAN MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename  : PE_Const.H
**     Project   : demo_serial_bootloader
**     Processor : 56F807
**     Beantype  : PE_Const
**     Version   : Driver 01.01
**     Compiler  : Metrowerks DSP C Compiler
**     Date/Time : 04/02/2005, 12.58
**     Abstract  :
**         This bean "PE_Const" contains internal definitions
**         of the constants.
**     Settings  :
**     Contents  :
**         No public methods
**
**     (c) Copyright UNIS, spol. s r.o. 1997-2004
**     UNIS, spol. s r.o.
**     Jundrovska 33
**     624 00 Brno
**     Czech Republic
**     http      : www.processorexpert.com
**     mail      : info@processorexpert.com
** ###################################################################*/

#ifndef __PE_Const_H
#define __PE_Const_H

/* Constants for detecting running mode */
#define HIGH_SPEED        0            /* High speed */
#define LOW_SPEED         1            /* Low speed */
#define SLOW_SPEED        2            /* Slow speed */

/* Reset cause constants */
#define RSTSRC_POR        4            /* Power-on reset        */
#define RSTSRC_PIN        8            /* External reset bit    */
#define RSTSRC_COP        16           /* COP reset             */

/* Memory modes */
#define INT_EXT_MODE      0            /* Internal & external memory mode */
#define EXT_MODE          1            /* External memory mode */

#endif /* _PE_Const_H */
/*
** ###################################################################
**
**     This file was created by UNIS Processor Expert 2.95 [03.58]
**     for the Freescale 56800 series of microcontrollers.
**
** ###################################################################
*/
