
set(LIBNAME vislab_YARP)

if(NOT LIBVISLAB_YARP_FOUND)

    message(STATUS "Using LIBVISLAB_YARPConfig.cmake")
    
    set(LIB_DIR ${LIBVISLAB_YARP_DIR})
    set(LIBVISLAB_YARP_INCLUDE_DIRS ${LIB_DIR}/src)
    
    
    if(NESTED_BUILD)
    
      set(LIBVISLAB_YARP_LIBRARIES ${LIBNAME})
    
    else(NESTED_BUILD)
    
      find_library(LIBVISLAB_YARP_LIBRARIES ${LIBNAME} ${ICUB_DIR}/lib ${LIB_DIR})  
    
      if(NOT LIBVISLAB_YARP_LIBRARIES)
    
        find_library(LIBVISLAB_YARP_LIBRARIES_RELEASE ${LIBNAME} 
    		         ${ICUB_DIR}/lib/Release ${LIB_DIR}/Release NO_DEFAULT_PATH)
        find_library(LIBVISLAB_YARP_LIBRARIES_DEBUG ${LIBNAME} 
    		         ${ICUB_DIR}/lib/Debug ${LIB_DIR}/Debug NO_DEFAULT_PATH)
    
        if(LIBVISLAB_YARP_LIBRARIES_RELEASE AND NOT LIBVISLAB_YARP_LIBRARIES_DEBUG)
           set(LIBVISLAB_YARP_LIBRARIES ${LIBVISLAB_YARP_LIBRARIES_RELEASE} CACHE PATH "release version of library" FORCE)
        endif(LIBVISLAB_YARP_LIBRARIES_RELEASE AND NOT LIBVISLAB_YARP_LIBRARIES_DEBUG)
    
        if(LIBVISLAB_YARP_LIBRARIES_DEBUG AND NOT LIBVISLAB_YARP_LIBRARIES_RELEASE)
           set(LIBVISLAB_YARP_LIBRARIES ${LIBVISLAB_YARP_LIBRARIES_DEBUG} CACHE PATH "debug version of library" FORCE)
        endif(LIBVISLAB_YARP_LIBRARIES_DEBUG AND NOT LIBVISLAB_YARP_LIBRARIES_RELEASE)
    
        if(LIBVISLAB_YARP_LIBRARIES_DEBUG AND LIBVISLAB_YARP_LIBRARIES_RELEASE)
           set(LIBVISLAB_YARP_LIBRARIES optimized ${LIBVISLAB_YARP_LIBRARIES_RELEASE}
    			                 debug ${LIBVISLAB_YARP_LIBRARIES_DEBUG} CACHE PATH "debug and release version of library" FORCE)
        endif(LIBVISLAB_YARP_LIBRARIES_DEBUG AND LIBVISLAB_YARP_LIBRARIES_RELEASE)
    
        mark_as_advanced(LIBVISLAB_YARP_LIBRARIES_RELEASE)
        mark_as_advanced(LIBVISLAB_YARP_LIBRARIES_DEBUG)
    
      endif(NOT LIBVISLAB_YARP_LIBRARIES)
    
    endif(NESTED_BUILD)
    
	if(${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION} LESS 2.6)

      if(LIBVISLAB_YARP_INCLUDE_DIRS AND LIBVISLAB_YARP_LIBRARIES)
        SET(LIBVISLAB_YARP_FOUND 1)
      else(LIBVISLAB_YARP_INCLUDE_DIRS AND LIBVISLAB_YARP_LIBRARIES)
        SET(LIBVISLAB_YARP_FOUND 0)
      endif(LIBVISLAB_YARP_INCLUDE_DIRS AND LIBVISLAB_YARP_LIBRARIES)

	else(${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION} LESS 2.6)

    	find_package_handle_standard_args(LIBHANDCTRL DEFAULT_MSG LIBVISLAB_YARP_INCLUDE_DIRS LIBVISLAB_YARP_LIBRARIES)

    endif(${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION} LESS 2.6)
    
    
endif(NOT LIBVISLAB_YARP_FOUND)
