
IF(NOT FASTFILT_FOUND)

    MESSAGE(STATUS "Using FASTFILTConfig.cmake")
    
    SET(LIB_DIR ${FASTFILT_DIR})
    SET(FASTFILT_INCLUDE_DIRS ${LIB_DIR}/include)
    
    
    IF(NESTED_BUILD)
    
      SET(FASTFILT_LIBRARIES fastFilt)
    
    ELSE(NESTED_BUILD)
    
      FIND_LIBRARY(FASTFILT_LIBRARIES fastFilt ${ICUB_DIR}/lib ${LIB_DIR})  
    
      IF(NOT FASTFILT_LIBRARIES)
    
        FIND_LIBRARY(FASTFILT_LIBRARIES_RELEASE fastFilt 
    		         ${ICUB_DIR}/lib/Release ${LIB_DIR}/Release NO_DEFAULT_PATH)
        FIND_LIBRARY(FASTFILT_LIBRARIES_DEBUG fastFilt
    		         ${ICUB_DIR}/lib/Debug ${LIB_DIR}/Debug NO_DEFAULT_PATH)
    
        IF(FASTFILT_LIBRARIES_RELEASE AND NOT FASTFILT_LIBRARIES_DEBUG)
           SET(FASTFILT_LIBRARIES ${FASTFILT_LIBRARIES_RELEASE} CACHE PATH "release version of library" FORCE)
        ENDIF(FASTFILT_LIBRARIES_RELEASE AND NOT FASTFILT_LIBRARIES_DEBUG)
    
        IF(FASTFILT_LIBRARIES_DEBUG AND NOT FASTFILT_LIBRARIES_RELEASE)
           SET(FASTFILT_LIBRARIES ${FASTFILT_LIBRARIES_DEBUG} CACHE PATH "debug version of library" FORCE)
        ENDIF(FASTFILT_LIBRARIES_DEBUG AND NOT FASTFILT_LIBRARIES_RELEASE)
    
        IF(FASTFILT_LIBRARIES_DEBUG AND FASTFILT_LIBRARIES_RELEASE)
           SET(FASTFILT_LIBRARIES optimized ${FASTFILT_LIBRARIES_RELEASE}
    			                  debug ${FASTFILT_LIBRARIES_DEBUG} CACHE PATH "debug and release version of library" FORCE)
        ENDIF(FASTFILT_LIBRARIES_DEBUG AND FASTFILT_LIBRARIES_RELEASE)
    
        MARK_AS_ADVANCED(FASTFILT_LIBRARIES_RELEASE)
        MARK_AS_ADVANCED(FASTFILT_LIBRARIES_DEBUG)
    
      ENDIF(NOT FASTFILT_LIBRARIES)      
    
    ENDIF(NESTED_BUILD)
    
    IF(FASTFILT_INCLUDE_DIRS AND FASTFILT_LIBRARIES)
       SET(FASTFILT_FOUND TRUE)
    ELSE(FASTFILT_INCLUDE_DIRS AND FASTFILT_LIBRARIES)
       SET(FASTFILT_FOUND FALSE)
    ENDIF(FASTFILT_INCLUDE_DIRS AND FASTFILT_LIBRARIES)
    
ENDIF(NOT FASTFILT_FOUND)


