
MESSAGE(STATUS "FASTFILT Library")

SET(FASTFILT_INCLUDE_DIRS ${FASTFILT_DIR}/include)

IF (NESTED_BUILD)
  SET(FASTFILT_LIBRARIES fastFilt)
ELSE (NESTED_BUILD)
  FIND_LIBRARY(FASTFILT_LIBRARIES fastFilt ${FASTFILT_DIR})
ENDIF (NESTED_BUILD)

