/*
 * SPDX-FileCopyrightText: 2023-2023 Istituto Italiano di Tecnologia (IIT)
 * SPDX-License-Identifier: LGPL-2.1-or-later
 */


// Generated by yarpDeviceParamParserGenerator (2.0)
// This is an automatically generated file. Please do not edit it.
// It will be re-generated if the cmake flag ALLOW_DEVICE_PARAM_PARSER_GERNERATION is ON.

// Generated on: Mon Sep 15 14:23:48 2025


#ifndef RAWVALUESPUBLISHERREMAPPER_PARAMSPARSER_H
#define RAWVALUESPUBLISHERREMAPPER_PARAMSPARSER_H

#include <yarp/os/Searchable.h>
#include <yarp/dev/IDeviceDriverParams.h>
#include <string>
#include <cmath>

/**
* This class is the parameters parser for class RawValuesPublisherRemapper.
*
* These are the used parameters:
* | Group name | Parameter name | Type           | Units | Default Value | Required | Description                             | Notes |
* |:----------:|:--------------:|:--------------:|:-----:|:-------------:|:--------:|:---------------------------------------:|:-----:|
* | -          | axesNames      | vector<string> | -     | -             | 1        | List of axes names                      | -     |
* | -          | joints         | int            | -     | 1             | 0        | Number of control boards to be remapped | -     |
*
* The device can be launched by yarpdev using one of the following examples (with and without all optional parameters):
* \code{.unparsed}
* yarpdev --device rawvaluespublisherremapper --axesNames <mandatory_value> --joints 1
* \endcode
*
* \code{.unparsed}
* yarpdev --device rawvaluespublisherremapper --axesNames <mandatory_value>
* \endcode
*
*/

class RawValuesPublisherRemapper_ParamsParser : public yarp::dev::IDeviceDriverParams
{
public:
    RawValuesPublisherRemapper_ParamsParser();
    ~RawValuesPublisherRemapper_ParamsParser() override = default;

public:
    const std::string m_device_classname = {"RawValuesPublisherRemapper"};
    const std::string m_device_name = {"rawvaluespublisherremapper"};
    bool m_parser_is_strict = false;
    struct parser_version_type
    {
         int major = 2;
         int minor = 0;
    };
    const parser_version_type m_parser_version = {};

    std::string m_provided_configuration;

    const std::string m_axesNames_defaultValue = {""};
    const std::string m_joints_defaultValue = {"1"};

    std::vector<std::string> m_axesNames = {}; //This default value is autogenerated. It is highly recommended to provide a suggested value also for mandatory parameters.
    int m_joints = {1};

    bool          parseParams(const yarp::os::Searchable & config) override;
    std::string   getDeviceClassName() const override { return m_device_classname; }
    std::string   getDeviceName() const override { return m_device_name; }
    std::string   getDocumentationOfDeviceParams() const override;
    std::vector<std::string> getListOfParams() const override;
    bool getParamValue(const std::string& paramName, std::string& paramValue) const override;
    std::string   getConfiguration() const override;
};

#endif
