
IF(NOT YARPIFLIB_FOUND)

    MESSAGE(STATUS "Using YARPIFLIBConfig.cmake")
    
    SET(LIB_DIR $ENV{YARPIFLIB_DIR})
    SET(YARPIFLIB_INCLUDE_DIRS ${LIB_DIR})
    
    FIND_LIBRARY(YARPIFLIB_LIBRARIES yarpIFlib ${LIB_DIR})  
            
    # Add YARP dependencies
    FIND_PACKAGE(YARP)
    SET(YARPIFLIB_LIBRARIES ${YARPIFLIB_LIBRARIES} ${YARP_LIBRARIES})
    
    IF(YARPIFLIB_INCLUDE_DIRS AND YARPIFLIB_LIBRARIES)
       SET(YARPIFLIB_FOUND TRUE)
    ELSE(YARPIFLIB_INCLUDE_DIRS AND YARPIFLIB_LIBRARIES)
       SET(YARPIFLIB_FOUND FALSE)
    ENDIF(YARPIFLIB_INCLUDE_DIRS AND YARPIFLIB_LIBRARIES)
    
ENDIF(NOT YARPIFLIB_FOUND)

