# Created:
# DRAGONFLYAPI_INC_DIRS   - Directories to include to use dragonfly API
# DRAGONFLYAPI_LIB        - Default library to link against to use the dragonfly API
# DRAGONFLYAPI_FOUND      - If false, don't try to use dragonfly API

IF(NOT DRAGONFLYAPI_FOUND)
  IF(WIN32)
    SET(DRAGONFLYAPI_DIR $ENV{DRAGONFLYAPI_DIR} CACHE PATH "Path to DRAGONFLYAPI")
    SET(DRAGONFLYAPI_INC_DIRS ${DRAGONFLYAPI_DIR}/include)
  
  ELSE(WIN32)  
	FIND_LIBRARY(lib_raw1394 raw1394)
	FIND_LIBRARY(lib_dc1394 dc1394)
	IF (lib_raw1394 AND lib_dc1394)
	  SET(DRAGONFLYAPI_LIB ${lib_raw1394} ${lib_dc1394})
	ENDIF (lib_raw1394 AND lib_dc1394)
  ENDIF (WIN32)

  IF(DRAGONFLYAPI_LIB)
    SET(DRAGONFLYAPI_FOUND TRUE)
  ELSE(DRAGONFLYAPI_LIB)
    SET(DRAGONFLYAPI_FOUND FALSE)
    SET(DRAGONFLYAPI_INC_DIRS)
    SET(DRAGONFLYAPI_LIB )
  ENDIF(DRAGONFLYAPI_LIB)

ENDIF(NOT DRAGONFLYAPI_FOUND)




