
include(FindPackageHandleStandardArgs)

IF (V4L2_INCLUDE_DIR AND V4L2_LIBRARY)
    # Already in cache, be silent
#    SET (LIBV4L2_FIND_QUIETLY TRUE)
ENDIF (V4L2_INCLUDE_DIR AND V4L2_LIBRARY)


IF (NOT V4L2_FOUND)
  FIND_PATH (V4L2_INCLUDE_DIR libv4l2.h)
  FIND_LIBRARY (V4L2_LIBRARY NAMES v4l2)

  IF (V4L2_INCLUDE_DIR AND V4L2_LIBRARY)
    SET (V4L2_FOUND TRUE)
  ENDIF( V4L2_INCLUDE_DIR AND V4L2_LIBRARY )
ENDIF ( NOT V4L2_FOUND)


IF( V4L2_FOUND )
  IF( NOT LIBV4L2_FIND_QUIETLY )
    MESSAGE( STATUS "Found LIBV4L2: ${V4L2_LIBRARY}")
  ENDIF( NOT LIBV4L2_FIND_QUIETLY )
else( V4L2_FOUND )
  IF( NOT LIBV4L2_FIND_QUIETLY )
    MESSAGE( STATUS "LIBV4L2 was NOT found")
  ENDIF( NOT LIBV4L2_FIND_QUIETLY )
ENDIF( V4L2_FOUND )
