# Created:
# DRAGONFLYAPI_INC_DIRS   - Directories to include to use dragonfly API
# DRAGONFLYAPI_LIB        - Default library to link against to use the dragonfly API
# DRAGONFLYAPI_FOUND      - If false, don't try to use dragonfly API

IF(NOT DRAGONFLYAPI_FOUND)
    SET(DRAGONFLYAPI_DIR $ENV{DRAGONFLYAPI_DIR} CACHE PATH "Path to DRAGONFLYAPI")
    SET(DRAGONFLYAPI_INC_DIRS ${DRAGONFLYAPI_DIR}/include)
    
    IF(WIN32)
       FIND_LIBRARY(DRAGONFLYAPI_LIB ntcan ${DRAGONFLYAPI_DIR}/lib NO_DEFAULT_PATH)    
    ELSE(WIN32)  
       FIND_LIBRARY(DRAGONFLYAPI_LIB ntcan ${DRAGONFLYAPI_DIR}/lib NO_DEFAULT_PATH)    
    ENDIF(WIN32)
    
    IF(DRAGONFLYAPI_LIB)
       SET(DRAGONFLYAPI_FOUND TRUE)
    ELSE(DRAGONFLYAPI_LIB)
       SET(DRAGONFLYAPI_FOUND FALSE)
       SET(DRAGONFLYAPI_INC_DIRS)
       SET(DRAGONFLYAPI_LIB )
    ENDIF(DRAGONFLYAPI_LIB)

ENDIF(NOT DRAGONFLYAPI_FOUND)




