#!/bin/bash

me=$0
key=$1
shift

BASE_PATH="cluster"

if [ "k$key" = "k" ]; then
	echo Call as:
	echo "   $me all <command>"
	echo "   $me on <machine> <command>"
	echo "   $me start <machine> <nickname> <command>"
	echo "   $me stop <machine> <nickname>"
	echo "   $me stop <nickname>"
	echo "   $me stopmore <machine> <nickname>"
	echo "   $me stopmore <nickname>"
	echo "synonyms:"
	echo "   bg start"
	echo "   kill stop"
	echo "   killmore stopmore"
	exit 1
else
	echo $*
fi

case "$key" in

  on)

	if [ "k$1" = "k" ]; then
	    echo "Call as: $me on <machine name> <command>"
	else
	    machine=$1
	    shift
	    ssh $machine "SHELL=/bin/bash; ( echo \"#!/bin/bash\"; echo \"PS1=fake\"; echo \"source ./.bashrc\"; echo \"export DISPLAY=:0.0\"; if [ ! "k"'\$ICUB_ROOT' = "k" ]; then echo cd '\$ICUB_ROOT/src/cluster'; else echo cd $BASE_PATH; fi; echo \"exec \"$*\"\" ) | bash -s"
	fi
	;;

  all)

	if [ "k$1" = "k" ]; then
	    echo "please pass the name of a command to run";
	else
	    echo "Command is: $*"    
	    for f in `cat machines.txt | sed "s/#.*//g"`; do
		echo "========================================================"
		echo "=== $f: $*"
		$me on $f $*
	    done
	fi
	;;

  start)

	if [ "k$1" = "k" ]; then
	    echo "Call as: $me bg <machine-name> <process-nickname> <command>"
	    echo "The nickname can be used for killing"
	    echo "(needed for windows/unix portability in process naming)"
	else
	    target=$1
	    nick=$2
	    shift
	    shift
	    cmd=$1
	    shift
	    ssh -f $target "SHELL=/bin/bash; ( echo \"#!/bin/bash\"; echo \"PS1=fake\"; echo \"source ./.bashrc\"; echo \"export DISPLAY=:0.0\"; if [ ! "k"'\$ICUB_ROOT' = "k" ]; then echo cd '\$ICUB_ROOT/src/cluster'; else echo cd $BASE_PATH; fi; echo \"./yarprun stop $nick\"; echo \"echo \\\$\\\$ > /tmp/pid-$nick\" ; echo exec \"$cmd $*\" ) > /tmp/cmd-$nick ; chmod a+x /tmp/cmd-$nick; /tmp/cmd-$nick "
	fi
	;;

  stopmore)

	if [ "k$1" = "k" ]; then
	    echo "Call as: $me stopmore <process-nickname>"
	    echo "Or:      $me stopmore <machine> <process-nickname>"
	else
	    echo $0 $1 $2 $3

	    if [ "k$2" = "k" ]; then
		    nick=$1
			res=`sh -c "cat /tmp/retired-$nick 2> /dev/null"`
			if [ "k$res" = "k" ]; then
				echo "$nick: no process killed"
			else
				echo "$nick: kill -9 $res"
				kill -9 $res
			fi
	    else
			$0 on $1 ./yarprun stopmore $2
	    fi
	fi
	;;

  stop)

	if [ "k$1" = "k" ]; then
	    echo "Call as: stop <process-nickname>"
	    echo "Or:      stop <machine> <process-nickname>"
	else
	    echo $0 $1 $2 $3

	    if [ "k$2" = "k" ]; then
		    nick=$1
			res=`sh -c "cat /tmp/pid-$nick 2> /dev/null"`
			if [ "k$res" = "k" ]; then
				echo "$nick: no process killed"
			else
				echo "$nick: kill $res"
				kill $res
				mv /tmp/pid-$nick /tmp/retired-$nick
			fi
	    else
			$0 on $1 ./yarprun stop $2
	    fi
	fi
	;;

   *)
	echo $key not recognized
	exit 1

esac
