#!/bin/sh

# Copyright (C) 2007 Jonas Ruesch
# CopyPolicy: Released under the terms of the GNU GPL v2.0.

# Robot Name
NAME_ROBOT=icub

EXECUTABLE_PATH=$ICUB_DIR/bin

# Module: Emotion Interface
EMOTION_INTERFACE_EXECUTABLE=emotionInterface
EMOTION_INTERFACE_CONFIG_FILE=emotions.ini
EMOTION_INTERFACE_NAME=/$NAME_ROBOT/face/emotions
EMOTION_INTERFACE_PORT_IN=$EMOTION_INTERFACE_NAME/in
EMOTION_INTERFACE_PORT_OUT=$EMOTION_INTERFACE_NAME/out