
function main()
clear all
close all
clc

d='step1';
[data]=chooseFile(d);
data=data(31287:46297,:);
time=[0:0.01:0.01*(length(data)-1)];
figure
length(data)
length(time)
plot(time,data(:,2),'LineWidth',2), hold on, plot(time, data(:,3),'r','LineWidth',2)
axis([0 150 -2 2])
% d='rightArm2';
% [data,l]=chooseFile(d);
% [H,f] = transferFCT(data,l);
% semilogx(f,20*log10(abs(H(1:end))),'r'),axis([1 20 -90 0]), hold on
set(gcf,'Color',[1,1,1])
yl=ylabel('torque [Nm]');
set(yl,'Interpreter','latex','FontSize',14);
xl=xlabel('Time [s]');
set(xl,'Interpreter','latex','FontSize',14);
ll=legend('$\tau_d$','$\tau$');
set(ll,'Interpreter','latex','FontSize',14,'Location','SouthEast');

grid on
figure
plot(time,data(:,2)-data(:,3),'LineWidth',2), 
axis([0 150 -1.5 1.5])
% d='rightArm2';
% [data,l]=chooseFile(d);
% [H,f] = transferFCT(data,l);
% semilogx(f,20*log10(abs(H(1:end))),'r'),axis([1 20 -90 0]), hold on
set(gcf,'Color',[1,1,1])
yl=ylabel('torque error $\tau_d-\tau$[Nm]');
set(yl,'Interpreter','latex','FontSize',14);
xl=xlabel('Time [s]');
set(xl,'Interpreter','latex','FontSize',14);
grid

% % % 
    
    function [data,l]=chooseFile(d)
        if(strcmp(d,'step1'))
            disp('left')
            data=importfile('stepResponce.dat');
        end
    end

    function [newData1] = importfile(fileToRead1)
    %IMPORTFILE(FILETOREAD1)
    %  Imports data from the specified file
    %  FILETOREAD1:  file to read

    %  Auto-generated by MATLAB on 24-Feb-2010 17:02:18

    % Import the file
    rawData1 = importdata(fileToRead1);

    % For some simple files (such as a CSV or JPEG files), IMPORTDATA might
    % return a simple array.  If so, generate a structure so that the output
    % matches that from the Import Wizard.
    [~,name] = fileparts(fileToRead1);
%     newData1.(genvarname(name)) = rawData1;
    newData1 = rawData1;
    end
end
