IF(NOT IFC_FOUND)
  IF (NESTED_BUILD)
    FIND_PACKAGE(IKIN)
    MESSAGE(STATUS "iFC: I'm in nested build")
    SET(LIB_DIR ${IFC_DIR})
    SET(IFC_LIBRARIES iFC ${IKIN_LIBRARIES})
    SET(IFC_INCLUDE_DIRS ${LIB_DIR}/include ${IKIN_INCLUDE_DIRS})
  ELSE(NESTED_BUILD)
    SET(LIB_DIR ${IFC_DIR})    
    MESSAGE(STATUS "I'm NOT in nested build")
    #SET(LIB_DIR ${ICUB_DIR}/src/iFC)	
    SET(IFC_INCLUDE_DIRS ${LIB_DIR}/include)

    FIND_PACKAGE(IKIN)	
    
    FIND_LIBRARY(IFC_LIBRARIES iFC ${IKIN_LIBRARIES} ${ICUB_DIR}/lib ${LIB_DIR})  
    FIND_LIBRARY(IFC_LIBRARIES_RELEASE iFC ${IKIN_LIBRARIES} ${ICUB_DIR}/lib/Release ${LIB_DIR}/Release NO_DEFAULT_PATH)
    FIND_LIBRARY(IFC_LIBRARIES_DEBUG iFC 
      ${ICUB_DIR}/lib/Debug ${LIB_DIR}/Debug NO_DEFAULT_PATH)

    #MESSAGE(STATUS "Message:" ${IFC_LIBRARIES})    

    IF(IFC_LIBRARIES_RELEASE AND NOT IFC_LIBRARIES_DEBUG)
      SET(IFC_LIBRARIES_RELEASE ${IFC_LIBRARIES_RELEASE})
      SET(IFC_LIBRARIES ${IFC_LIBRARIES_RELEASE} CACHE PATH "release version of library" FORCE)
    ENDIF(IFC_LIBRARIES_RELEASE AND NOT IFC_LIBRARIES_DEBUG)
    
    IF(IFC_LIBRARIES_DEBUG AND NOT IFC_LIBRARIES_RELEASE)
      SET(IFC_LIBRARIES_DEBUG ${IFC_LIBRARIES_DEBUG})
      SET(IFC_LIBRARIES ${IFC_LIBRARIES_DEBUG} CACHE PATH "debug version of library" FORCE)
    ENDIF(IFC_LIBRARIES_DEBUG AND NOT IFC_LIBRARIES_RELEASE)
    
    IF(IFC_LIBRARIES_DEBUG AND IFC_LIBRARIES_RELEASE)
      SET(IFC_LIBRARIES_RELEASE ${IFC_LIBRARIES_RELEASE})
      SET(IFC_LIBRARIES_DEBUG ${IFC_LIBRARIES_DEBUG})
      SET(IFC_LIBRARIES optimized ${IFC_LIBRARIES_RELEASE}
    	debug ${IFC_LIBRARIES_DEBUG} CACHE PATH "debug and release version of library" FORCE)
    ENDIF(IFC_LIBRARIES_DEBUG AND IFC_LIBRARIES_RELEASE)
    
    MARK_AS_ADVANCED(IFC_LIBRARIES_RELEASE)
    MARK_AS_ADVANCED(IFC_LIBRARIES_DEBUG)
    
    # Add YARP dependencies
    FIND_PACKAGE(YARP)
    SET(IFC_LIBRARIES ${IFC_LIBRARIES} ${YARP_LIBRARIES})

  ENDIF(NESTED_BUILD)
  MESSAGE(STATUS "iFC: ???")

  IF(IFC_INCLUDE_DIRS AND IFC_LIBRARIES)
    SET(IFC_FOUND TRUE)
  ELSE(IFC_INCLUDE_DIRS AND IFC_LIBRARIES)
    SET(IFC_FOUND FALSE)
  ENDIF(IFC_INCLUDE_DIRS AND IFC_LIBRARIES)

  SET(IFC_FOUND TRUE)
ELSE(NOT IFC_FOUND)
  MESSAGE(STATUS "iFC found")
ENDIF(NOT IFC_FOUND)
