
MESSAGE(STATUS "CAMERA Library")

IF (NESTED_BUILD)
  SET(CAMERA_LIBRARIES camera)
ELSE (NESTED_BUILD)
  #FIND_LIBRARY(CAMERA_LIBRARIES camera ${CAMERA_DIR})
ENDIF (NESTED_BUILD)

SET(CAMERA_INCLUDE_DIRS ${CAMERA_DIR}/include)

