// Class automatically generated by Dev-C++ New Class wizard

#include <gsl/gsl_matrix.h>
#include <gsl/gsl_blas.h>

#ifndef ROBMATRIX_H
#define ROBMATRIX_H

/*
 * A Matrix class for robotic
 */
class RobMatrix
{
	public:
		gsl_vector* getvector( int line, int column, int nelem);
		gsl_vector* P();

		RobMatrix();
		RobMatrix( int val );
		~RobMatrix();
		RobMatrix(double alpha, double a, double ofth, double d);
		RobMatrix(double x, double y, double z);
		RobMatrix(double x, double y, double z, int val);
		RobMatrix(double r11, double r12, double r13,double r21, double r22, double r23,double r31, double r32, double r33);

		RobMatrix operator*(const RobMatrix &param);
		RobMatrix operator+(const RobMatrix &param);
		RobMatrix& operator=(const RobMatrix &M);

		RobMatrix Inv(double th);
		RobMatrix Inv();
		RobMatrix V(double th);

        void print();
		double M[4][4];
   	private:
	    RobMatrix Inv(double alpha, double a, double d, double th);
		// No description
		double a, alpha, d, ofth;
};

#endif // ROBMATRIX_H

