MESSAGE(STATUS "MathLib Library")

#FIND_LIBRARY(MathLib_LIBRARIES MathLib ${MathLib_DIR}/lib)

#IF (NOT MathLib_LIBRARIES)
  SET(MathLib_LIBRARIES MathLib)
#ELSE (NESTED_BUILD)
#  FIND_LIBRARY(MathLib_LIBRARIES MathLib ${MathLib_DIR}/lib)
#ENDIF (NOT MathLib_LIBRARIES)

#IF (NESTED_BUILD)
#  SET(MathLib_LIBRARIES MathLib)
#ELSE (NESTED_BUILD)
#  FIND_LIBRARY(MathLib_LIBRARIES MathLib ${MathLib_DIR}/lib)
#ENDIF (NESTED_BUILD)

SET(MathLib_INCLUDE_DIR ${MathLib_DIR}/include)

