/*
 * SPDX-FileCopyrightText: 2006-2021 Istituto Italiano di Tecnologia (IIT)
 * SPDX-License-Identifier: BSD-3-Clause
 */

// Autogenerated by Thrift Compiler (0.14.1-yarped)
//
// This is an automatically generated file.
// It could get re-generated if the ALLOW_IDL_GENERATION flag is on.

#ifndef YARP_THRIFT_GENERATOR_STRUCT_RAWVALUESKEYMETADATA_H
#define YARP_THRIFT_GENERATOR_STRUCT_RAWVALUESKEYMETADATA_H

#include <yarp/os/Wire.h>
#include <yarp/os/idl/WireTypes.h>

namespace iCub {

class rawValuesKeyMetadata :
        public yarp::os::idl::WirePortable
{
public:
    // Fields
    std::vector<std::string> rawValueNames{};
    std::vector<std::string> axesNames{};
    std::int32_t size{0};

    // Default constructor
    rawValuesKeyMetadata() = default;

    // Constructor with field values
    rawValuesKeyMetadata(const std::vector<std::string>& rawValueNames,
                         const std::vector<std::string>& axesNames,
                         const std::int32_t size);

    // Read structure on a Wire
    bool read(yarp::os::idl::WireReader& reader) override;

    // Read structure on a Connection
    bool read(yarp::os::ConnectionReader& connection) override;

    // Write structure on a Wire
    bool write(const yarp::os::idl::WireWriter& writer) const override;

    // Write structure on a Connection
    bool write(yarp::os::ConnectionWriter& connection) const override;

    // Convert to a printable string
    std::string toString() const;

    // If you want to serialize this class without nesting, use this helper
    typedef yarp::os::idl::Unwrapped<rawValuesKeyMetadata> unwrapped;

private:
    // read/write rawValueNames field
    bool read_rawValueNames(yarp::os::idl::WireReader& reader);
    bool write_rawValueNames(const yarp::os::idl::WireWriter& writer) const;
    bool nested_read_rawValueNames(yarp::os::idl::WireReader& reader);
    bool nested_write_rawValueNames(const yarp::os::idl::WireWriter& writer) const;

    // read/write axesNames field
    bool read_axesNames(yarp::os::idl::WireReader& reader);
    bool write_axesNames(const yarp::os::idl::WireWriter& writer) const;
    bool nested_read_axesNames(yarp::os::idl::WireReader& reader);
    bool nested_write_axesNames(const yarp::os::idl::WireWriter& writer) const;

    // read/write size field
    bool read_size(yarp::os::idl::WireReader& reader);
    bool write_size(const yarp::os::idl::WireWriter& writer) const;
    bool nested_read_size(yarp::os::idl::WireReader& reader);
    bool nested_write_size(const yarp::os::idl::WireWriter& writer) const;
};

} // namespace iCub

#endif // YARP_THRIFT_GENERATOR_STRUCT_RAWVALUESKEYMETADATA_H
