MESSAGE(STATUS "GLTools Library")

IF (NESTED_BUILD)
  SET(GLTools_LIBRARIES GLTools)
ELSE (NESTED_BUILD)
  FIND_LIBRARY(GLTools_LIBRARIES GLTools ${GLTools_DIR})
ENDIF (NESTED_BUILD)

SET(GLTools_INCLUDE_DIR ${GLTools_DIR}/include)

