MESSAGE(STATUS "GLTools Library")

#FIND_LIBRARY(GLTools_LIBRARIES GLTools ${GLTools_DIR}/lib)

#IF (NOT GLTools_LIBRARIES)
  SET(GLTools_LIBRARIES GLTools)
#ELSE (NESTED_BUILD)
#  FIND_LIBRARY(GLTools_LIBRARIES GLTools ${GLTools_DIR}/lib)
#ENDIF (NOT GLTools_LIBRARIES)

#IF (NESTED_BUILD)
#  SET(GLTools_LIBRARIES GLTools)
#ELSE (NESTED_BUILD)
#  FIND_LIBRARY(GLTools_LIBRARIES GLTools ${GLTools_DIR}/lib)
#ENDIF (NESTED_BUILD)

SET(GLTools_INCLUDE_DIR ${GLTools_DIR}/include)

