
function main()
clear all
close all
clc
d='leftArm';
[data]=chooseFile(d);
[H,f] = transferFCT(data);
semilogx(f,20*log10(abs(H(1:end))),'--b'),axis([1 20 -90 0]), hold on
d='rightArm';
[data]=chooseFile(d);
[H,f] = transferFCT(data);
semilogx(f,20*log10(abs(H(1:end))),'--r'),axis([1 20 -90 0]), hold on
d='leftArm2';
[data]=chooseFile(d);
[H,f] = transferFCT(data);
semilogx(f,20*log10(abs(H(1:end))),'b'),axis([1 20 -90 0]), hold on
d='rightArm2';
[data]=chooseFile(d);
[H,f] = transferFCT(data);
semilogx(f,20*log10(abs(H(1:end))),'r'),axis([1 20 -90 0]), hold on
legend('LeftArm','RightArm','LeftArm2','RightArm2')

    function [H,f] = transferFCT(data)
        dt=data(1:end,1);
        dt=mean(dt);
        Fs = 1/dt;                    % Sampling frequency
        L = 402;                     % Length of signal
        t = (0:L-1)*dt;                % Time vector
        NFFT = 2^nextpow2(L); % Next power of 2 from length of y
        f = Fs/2*linspace(0,1,NFFT/2+1);
        index=0;
        maxA=0;
        f=[];
        for i=1:20
            ftData_i=data(((L*(i-1)+1):L*i),:);
            ftData(:,:,i)=ftData_i;
            fftData_i = fft(ftData_i,NFFT)/L;
            fftData(:,:,i)=fftData_i;
            [maxA,index] = max(2*abs(fftData_i(1:NFFT/2+1,2)));
            IN=fftData_i(index,2);
            OUT=fftData_i(index,3);
            H(i)=OUT/IN;
            f=[f;i];
        end
    end

    function [data]=chooseFile(d)
        if(strcmp(d,'leftArm'))
            disp('left')
            data=importfile('ftSweepData_leftarm.dat');
        elseif(strcmp(d,'leftArm2'))
            disp('left2')
            data=importfile('ftSweepData_leftarm2.dat');
        elseif(strcmp(d,'rightArm2'))
            disp('right2')
            data=importfile('ftSweepData_rightarm2.dat');
        else data=importfile('ftSweepData_rightarm.dat');
            disp('right')
        end
    end

    function [newData1] = importfile(fileToRead1)
    %IMPORTFILE(FILETOREAD1)
    %  Imports data from the specified file
    %  FILETOREAD1:  file to read

    %  Auto-generated by MATLAB on 24-Feb-2010 17:02:18

    % Import the file
    rawData1 = importdata(fileToRead1);

    % For some simple files (such as a CSV or JPEG files), IMPORTDATA might
    % return a simple array.  If so, generate a structure so that the output
    % matches that from the Import Wizard.
    [~,name] = fileparts(fileToRead1);
%     newData1.(genvarname(name)) = rawData1;
    newData1 = rawData1;
    end
end
