
MESSAGE(STATUS "RDOUT Library")

IF (NESTED_BUILD)
  SET(RDOUT_LIBRARIES rdout)
ELSE (NESTED_BUILD)
  FIND_LIBRARY(RDOUT_LIBRARIES rdout ${RDOUT_DIR})
ENDIF (NESTED_BUILD)

SET(RDOUT_INCLUDE_DIRS ${RDOUT_DIR}/include)

