
set(LIBNAME vislab)

if(NOT LIBVISLAB_FOUND)

    message(STATUS "Using LIBVISLABConfig.cmake")

    set(LIB_DIR ${LIBVISLAB_DIR})
    set(LIBVISLAB_INCLUDE_DIRS ${LIB_DIR}/src)

    find_package(LIBVISLAB_BASE)
    find_package(LIBVISLAB_YARP)

    set(LIBVISLAB_LIBRARIES ${LIBVISLAB_YARP_LIBRARIES} ${LIBVISLAB_BASE_LIBRARIES})
    set(LIBVISLAB_INCLUDE_DIRS ${LIBVISLAB_YARP_INCLUDE_DIRS} ${LIBVISLAB_BASE_INCLUDE_DIRS})

#	if(${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}${CMAKE_PATCH_VERSION} LESS 2.64)

      if(LIBVISLAB_INCLUDE_DIRS AND LIBVISLAB_LIBRARIES)
        SET(LIBVISLAB_FOUND 1)
      else(LIBVISLAB_INCLUDE_DIRS AND LIBVISLAB_LIBRARIES)
        SET(LIBVISLAB_FOUND 0)
      endif(LIBVISLAB_INCLUDE_DIRS AND LIBVISLAB_LIBRARIES)

#	else(${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}${CMAKE_PATCH_VERSION} LESS 2.64)

#    	find_package_handle_standard_args(LIBVISLAB DEFAULT_MSG LIBVISLAB_INCLUDE_DIRS LIBVISLAB_LIBRARIES)

#  endif(${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}${CMAKE_PATCH_VERSION} LESS 2.64)

endif(NOT LIBVISLAB_FOUND)
