/** ###################################################################
**     THIS BEAN MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename  : Timer.H
**     Project   : demo_serial_bootloader
**     Processor : 56F805
**     Beantype  : FreeCntr
**     Version   : Bean 01.014, Driver 01.20, CPU db: 2.71.075
**     Compiler  : Metrowerks DSP C Compiler
**     Date/Time : 01-Oct-04, 14:15
**     Abstract  :
**         This device "FreeCntr" implements a free running counter for
**         time measurement.
**     Settings  :
**         Timer name                  : TMRC01 (32-bit)
**         Compare name                : TMRC01_Compare
**         Counter shared              : No
**
**         High speed mode
**             Prescaler               : divide-by-1
**             Clock                   : 40000000 Hz
**           Period
**             Xtal ticks              : 8000000
**             microseconds            : 1000000
**             milliseconds            : 1000
**             seconds                 : 1
**             seconds (real)          : 1.0000000
**             Hz                      : 1
**           Frequency of counting (Bus clock / prescaler)
**             Hz                      : 40000000
**
**         Initialization:
**              Timer                  : Disabled
**
**         Timer registers
**              Counter                : TMRC1_CNTR [3341]
**              Mode                   : TMRC1_CTRL [3342]
**              Run                    : TMRC1_CTRL [3342]
**              Prescaler              : TMRC1_CTRL [3342]
**              Compare                : TMRC1_CMP1 [3336]
**
**         User handling procedure     : not specified
**     Contents  :
**         Enable    - byte Timer_Enable(void);
**         Disable   - byte Timer_Disable(void);
**         GetStatus - bool Timer_GetStatus(void);
**
**     (c) Copyright UNIS, spol. s r.o. 1997-2004
**     UNIS, spol. s r.o.
**     Jundrovska 33
**     624 00 Brno
**     Czech Republic
**     http      : www.processorexpert.com
**     mail      : info@processorexpert.com
** ###################################################################*/

#ifndef __Timer
#define __Timer

/* MODULE Timer. */

/*Include shared modules, which are used for whole project*/
#include "PE_Types.h"
#include "PE_Error.h"
#include "PE_Const.h"
#include "IO_Map.h"
#include "Cpu.h"

#define Timer_FChigh       40000000    /* Frequency of counting in high speed CPU mode */


void Timer_Init(void);
/*
** ===================================================================
**     Method      :  Timer_Init (bean FreeCntr)
**
**     Description :
**         This method is internal. It is used by Processor Expert
**         only.
** ===================================================================
*/

/* END Timer. */

#endif /* ifndef __Timer */
/*
** ###################################################################
**
**     This file was created by UNIS Processor Expert 0.00.00 [03.58]
**     for the Freescale 56800 series of microcontrollers.
**          !!! DEVELOPER VERSION FOR INTERNAL USAGE ONLY !!!
**
** ###################################################################
*/
