/*
 * Initial main.c file generated by Glade. Edit as required.
 * Glade will not overwrite this file.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <gtk/gtk.h>
#include "support.h"
#include "interface.h"
#include "functions.h"

imagedata imgPar;

GList * windowsList;
GList * pixbufList;
GtkWidget *mainMenuWindow;
gboolean changeZorder = TRUE;

int main (int argc, char *argv[])
{
	gtk_set_locale ();
	gtk_init (&argc, &argv);

	windowsList = NULL;
	pixbufList  = NULL;

	initPar();

	mainMenuWindow = create_main_menu_window ();

	gtk_widget_show (mainMenuWindow);

	g_signal_connect ((gpointer) mainMenuWindow, "destroy", G_CALLBACK(gtk_main_quit),NULL);

	gtk_main ();

	return 0;
}

#ifdef _MSC_VER
#include <windows.h>

int WINAPI WinMain(HINSTANCE hInstance,
                   HINSTANCE hPrevInstance,
                   LPSTR lpCmdLine,
                   int nCmdShow)
{
  return main (__argc, __argv);
}
#endif
 