
MESSAGE(STATUS "YARPQWIDGETS Library")

IF (NESTED_BUILD)
  SET(YARPQWIDGETS_LIBRARIES libYARP_QWidgets)
ELSE (NESTED_BUILD)
  FIND_LIBRARY(YARPQWIDGETS_LIBRARIES libYARP_QWidgets ${YARPQWIDGETS_DIR})
ENDIF (NESTED_BUILD)

SET(YARPQWIDGETS_INCLUDE_DIRS ${YARPQWIDGETS_DIR} ${YARPQWIDGETS_DIR}/include)

