COMPILE_FOR_MSVC8=false

SYSTEM_DESCRIPTION_FILE=get_sys_description.sh

CMAKE_OPTIONS="-DADD_IPOPT:BOOL=TRUE -DON_TEST_SERVER:BOOL=TRUE -DCREATE_GUIS_GTKMM:BOOL=TRUE -DCREATE_GUIS_QT:BOOL=TRUE -DCREATE_GUIS_GTK:BOOL=TRUE -DCOMPILE_NEW_FRAMEGRABBERGUI:BOOL=TRUE -DCOMPILE_FOR_TESTING:BOOL=TRUE"
