IF(NOT REINFORCEMENTLEARNING_FOUND)
    MESSAGE(STATUS "Using REINFORCEMENTLEARNINGConfig.cmake")
    
    SET(LIB_DIR ${REINFORCEMENTLEARNING_DIR})
    SET(REINFORCEMENTLEARNING_INCLUDE_DIRS)
    
    IF(NESTED_BUILD)
        SET(REINFORCEMENTLEARNING_LIBRARIES REINFORCEMENTLEARNING)
    ELSE(NESTED_BUILD)
        FIND_LIBRARY(REINFORCEMENTLEARNING_LIBRARIES REINFORCEMENTLEARNING ${ICUB_DIR}/lib ${LIB_DIR})  
        IF(NOT REINFORCEMENTLEARNING_LIBRARIES)
            FIND_LIBRARY(REINFORCEMENTLEARNING_LIBRARIES_RELEASE REINFORCEMENTLEARNING 
    		         ${ICUB_DIR}/lib/Release ${LIB_DIR}/Release NO_DEFAULT_PATH)
            FIND_LIBRARY(REINFORCEMENTLEARNING_LIBRARIES_DEBUG REINFORCEMENTLEARNING 
    		         ${ICUB_DIR}/lib/Debug ${LIB_DIR}/Debug NO_DEFAULT_PATH)
    
            IF(REINFORCEMENTLEARNING_LIBRARIES_RELEASE AND NOT REINFORCEMENTLEARNING_LIBRARIES_DEBUG)
                SET(REINFORCEMENTLEARNING_LIBRARIES_RELEASE ${REINFORCEMENTLEARNING_LIBRARIES_RELEASE})
                SET(REINFORCEMENTLEARNING_LIBRARIES ${REINFORCEMENTLEARNING_LIBRARIES_RELEASE} 
                    CACHE PATH "release version of library" FORCE)
            ENDIF(REINFORCEMENTLEARNING_LIBRARIES_RELEASE AND NOT REINFORCEMENTLEARNING_LIBRARIES_DEBUG)
    
            IF(REINFORCEMENTLEARNING_LIBRARIES_DEBUG AND NOT REINFORCEMENTLEARNING_LIBRARIES_RELEASE)
                SET(REINFORCEMENTLEARNING_LIBRARIES_DEBUG ${REINFORCEMENTLEARNING_LIBRARIES_DEBUG})
                SET(REINFORCEMENTLEARNING_LIBRARIES ${REINFORCEMENTLEARNING_LIBRARIES_DEBUG} 
                    CACHE PATH "debug version of library" FORCE)
            ENDIF(REINFORCEMENTLEARNING_LIBRARIES_DEBUG AND NOT REINFORCEMENTLEARNING_LIBRARIES_RELEASE)
    
            IF(REINFORCEMENTLEARNING_LIBRARIES_DEBUG AND REINFORCEMENTLEARNING_LIBRARIES_RELEASE)
                SET(REINFORCEMENTLEARNING_LIBRARIES_RELEASE ${REINFORCEMENTLEARNING_LIBRARIES_RELEASE})
                SET(REINFORCEMENTLEARNING_LIBRARIES_DEBUG ${REINFORCEMENTLEARNING_LIBRARIES_DEBUG})
                SET(REINFORCEMENTLEARNING_LIBRARIES optimized ${REINFORCEMENTLEARNING_LIBRARIES_RELEASE}
    	            debug ${REINFORCEMENTLEARNING_LIBRARIES_DEBUG} 
                    CACHE PATH "debug and release version of library" FORCE )
            ENDIF(REINFORCEMENTLEARNING_LIBRARIES_DEBUG AND REINFORCEMENTLEARNING_LIBRARIES_RELEASE)
    
            MARK_AS_ADVANCED(REINFORCEMENTLEARNING_LIBRARIES_RELEASE)
            MARK_AS_ADVANCED(REINFORCEMENTLEARNING_LIBRARIES_DEBUG)
    
        ENDIF(NOT REINFORCEMENTLEARNING_LIBRARIES)
    
    ENDIF(NESTED_BUILD)

    # Add YARP dependencies
    FIND_PACKAGE(YARP)
    SET(REINFORCEMENTLEARNING_LIBRARIES ${REINFORCEMENTLEARNING_LIBRARIES} ${YARP_LIBRARIES})
    
    IF(REINFORCEMENTLEARNING_INCLUDE_DIRS AND REINFORCEMENTLEARNING_LIBRARIES)
        SET(REINFORCEMENTLEARNING_FOUND TRUE)
    ELSE(REINFORCEMENTLEARNING_INCLUDE_DIRS AND REINFORCEMENTLEARNING_LIBRARIES)
        SET(REINFORCEMENTLEARNING_FOUND FALSE)
    ENDIF(REINFORCEMENTLEARNING_INCLUDE_DIRS AND REINFORCEMENTLEARNING_LIBRARIES)
    
ENDIF(NOT REINFORCEMENTLEARNING_FOUND)
