#!/bin/bash

MYSHELL="bash -c"

case "$1" in

 	start)
		echo "-0.5 0.0 0.35" | yarp write ... /iKinGazeCtrl/head/xd:i
		echo "set track 1" | yarp rpc /iKinGazeCtrl/head/rpc
		;;
 	stop)
	        echo "set track 0" | yarp rpc /iKinGazeCtrl/head/rpc
		;;

    *)
		echo "stop, start"
		;;
esac