#!/bin/bash

MYSHELL="bash -c"

case "$1" in

    	connect)
		yarp connect /icub/torso/state:o /dataDumper/torso/ctp
		;;

    	disconnect)
		yarp disconnect /icub/torso/state:o /dataDumper/torso/ctp
		;;
 	start)
		$MYSHELL "dataDumper --name /dataDumper/torso/ctp"&
		sleep 2
		;;
 	stop)
		echo "quit" | yarp rpc /dataDumper/torso/ctp/rpc
		;;

    *)
		echo "stop, start, kill"
		;;
esac