
MESSAGE(STATUS "SPMAP Library")

IF (NESTED_BUILD)
  SET(SPMAP_LIBRARIES spMap)
ELSE (NESTED_BUILD)
  FIND_LIBRARY(SPMAP_LIBRARIES spMap ${SPMAP_DIR})
ENDIF (NESTED_BUILD)

SET(SPMAP_INCLUDE_DIRS ${SPMAP_DIR}/include)

