MESSAGE(STATUS "StdTools Library")

IF (NESTED_BUILD)
  SET(StdTools_LIBRARIES StdTools)
ELSE (NESTED_BUILD)
  FIND_LIBRARY(StdTools_LIBRARIES StdTools ${StdTools_DIR})
ENDIF (NESTED_BUILD)

SET(StdTools_INCLUDE_DIR ${StdTools_DIR}/include)

