# Searches yarpmath package.
# Set:
# YARPMATH_FOUND
# YARPMATH_INCLUDE_DIRS
# YARPMATH_LIBRARIES

MESSAGE(STATUS "YARPMATH Library")

IF (NESTED_BUILD)
  SET(YARPMATH_LIBRARIES yarpMath)
ELSE (NESTED_BUILD)
  FIND_LIBRARY(YARPMATH_LIBRARIES
    NAMES yarpMath
    PATHS ${YARPMATH_DIR}/lib ${YARPMATH_DIR}
  )
ENDIF (NESTED_BUILD)

FIND_PATH(YARPMATH_INCLUDE_DIRS YARPMatrix.h  ${YARPMATH_DIR})

IF (YARPMATH_INCLUDE_DIRS AND YARPMATH_LIBRARIES)
  SET(YARPMATH_FOUND TRUE)
ELSE (YARPMATH_INCLUDE_DIRS AND YARPMATH_LIBRARIES)
  SET(YARPMATH_FOUND FALSE)
ENDIF(YARPMATH_INCLUDE_DIRS AND YARPMATH_LIBRARIES)
