
IF(NOT IDYN_FOUND)

    MESSAGE(STATUS "Using IDYNConfig.cmake")
    
    SET(LIB_DIR ${IDYN_DIR})
 
    SET(IDYN_INCLUDE_DIRS ${LIB_DIR}/include)
    
    
    IF(NESTED_BUILD)

      SET(IDYN_LIBRARIES iDyn)

    ELSE(NESTED_BUILD)
    
      FIND_LIBRARY(IDYN_LIBRARIES iDyn ${ICUB_DIR}/lib ${LIB_DIR})  
    
      IF(NOT IDYN_LIBRARIES)
    
        FIND_LIBRARY(IDYN_LIBRARIES_RELEASE iKin
    		         ${ICUB_DIR}/lib/Release ${LIB_DIR}/Release NO_DEFAULT_PATH)
        FIND_LIBRARY(IDYN_LIBRARIES_DEBUG iDynd
    		         ${ICUB_DIR}/lib/Debug ${LIB_DIR}/Debug NO_DEFAULT_PATH)
    
        IF(IDYN_LIBRARIES_RELEASE AND NOT IDYN_LIBRARIES_DEBUG)
           SET(IDYN_LIBRARIES ${IDYN_LIBRARIES_RELEASE} CACHE PATH "release version of library" FORCE)
        ENDIF(IDYN_LIBRARIES_RELEASE AND NOT IDYN_LIBRARIES_DEBUG)
    
        IF(IDYN_LIBRARIES_DEBUG AND NOT IDYN_LIBRARIES_RELEASE)
           SET(IDYN_LIBRARIES ${IDYN_LIBRARIES_DEBUG} CACHE PATH "debug version of library" FORCE)
        ENDIF(IDYN_LIBRARIES_DEBUG AND NOT IDYN_LIBRARIES_RELEASE)
    
        IF(IDYN_LIBRARIES_DEBUG AND IDYN_LIBRARIES_RELEASE)
           SET(IDYN_LIBRARIES optimized ${IDYN_LIBRARIES_RELEASE}
    			              debug ${IDYN_LIBRARIES_DEBUG} CACHE PATH "debug and release version of library" FORCE)
        ENDIF(IDYN_LIBRARIES_DEBUG AND IDYN_LIBRARIES_RELEASE)
    
        MARK_AS_ADVANCED(IDYN_LIBRARIES_RELEASE)
        MARK_AS_ADVANCED(IDYN_LIBRARIES_DEBUG)
    
      ENDIF(NOT IDYN_LIBRARIES)

      # Add YARP dependencies
      FIND_PACKAGE(YARP)
      SET(IDYN_LIBRARIES ${IDYN_LIBRARIES} ${YARP_LIBRARIES})
    
    ENDIF(NESTED_BUILD)
    
    # Add IKIN dependencies
    FIND_PACKAGE(IKIN REQUIRED)
    SET(IDYN_INCLUDE_DIRS ${IKIN_INCLUDE_DIRS})
    IF(NOT NESTED_BUILD)
       SET(IDYN_LIBRARIES ${IKIN_LIBRARIES})
    ENDIF(NOT NESTED_BUILD)
            
    IF(IDYN_INCLUDE_DIRS AND IDYN_LIBRARIES)
       SET(IDYN_FOUND TRUE)
    ELSE(IDYN_INCLUDE_DIRS AND IDYN_LIBRARIES)
       SET(IDYN_FOUND FALSE)
    ENDIF(IDYN_INCLUDE_DIRS AND IDYN_LIBRARIES)

ENDIF(NOT IDYN_FOUND)

