IF(NOT IDYN_FOUND)
  IF (NESTED_BUILD)
    FIND_PACKAGE(IKIN)
    MESSAGE(STATUS "iDyn: I'm in nested build")
    SET(LIB_DIR ${IDYN_DIR})
    SET(IDYN_LIBRARIES iDyn ${IKIN_LIBRARIES})
    SET(IDYN_INCLUDE_DIRS ${LIB_DIR}/include ${IKIN_INCLUDE_DIRS})
  ELSE(NESTED_BUILD)
    SET(LIB_DIR ${IDYN_DIR})    
    MESSAGE(STATUS "I'm NOT in nested build")
    #SET(LIB_DIR ${ICUB_DIR}/src/iDyn)	
    SET(IDYN_INCLUDE_DIRS ${LIB_DIR}/include)

    FIND_PACKAGE(IKIN)	
    
    FIND_LIBRARY(IDYN_LIBRARIES iDyn ${IKIN_LIBRARIES} ${ICUB_DIR}/lib ${LIB_DIR})  
    FIND_LIBRARY(IDYN_LIBRARIES_RELEASE iDyn ${IKIN_LIBRARIES} ${ICUB_DIR}/lib/Release ${LIB_DIR}/Release NO_DEFAULT_PATH)
    FIND_LIBRARY(IDYN_LIBRARIES_DEBUG iDyn 
      ${ICUB_DIR}/lib/Debug ${LIB_DIR}/Debug NO_DEFAULT_PATH)

    #MESSAGE(STATUS "Message:" ${IDYN_LIBRARIES})    

    IF(IDYN_LIBRARIES_RELEASE AND NOT IDYN_LIBRARIES_DEBUG)
      SET(IDYN_LIBRARIES_RELEASE ${IDYN_LIBRARIES_RELEASE})
      SET(IDYN_LIBRARIES ${IDYN_LIBRARIES_RELEASE} CACHE PATH "release version of library" FORCE)
    ENDIF(IDYN_LIBRARIES_RELEASE AND NOT IDYN_LIBRARIES_DEBUG)
    
    IF(IDYN_LIBRARIES_DEBUG AND NOT IDYN_LIBRARIES_RELEASE)
      SET(IDYN_LIBRARIES_DEBUG ${IDYN_LIBRARIES_DEBUG})
      SET(IDYN_LIBRARIES ${IDYN_LIBRARIES_DEBUG} CACHE PATH "debug version of library" FORCE)
    ENDIF(IDYN_LIBRARIES_DEBUG AND NOT IDYN_LIBRARIES_RELEASE)
    
    IF(IDYN_LIBRARIES_DEBUG AND IDYN_LIBRARIES_RELEASE)
      SET(IDYN_LIBRARIES_RELEASE ${IDYN_LIBRARIES_RELEASE})
      SET(IDYN_LIBRARIES_DEBUG ${IDYN_LIBRARIES_DEBUG})
      SET(IDYN_LIBRARIES optimized ${IDYN_LIBRARIES_RELEASE}
    	debug ${IDYN_LIBRARIES_DEBUG} CACHE PATH "debug and release version of library" FORCE)
    ENDIF(IDYN_LIBRARIES_DEBUG AND IDYN_LIBRARIES_RELEASE)
    
    MARK_AS_ADVANCED(IDYN_LIBRARIES_RELEASE)
    MARK_AS_ADVANCED(IDYN_LIBRARIES_DEBUG)
    
    # Add YARP dependencies
    FIND_PACKAGE(YARP)
    SET(IDYN_LIBRARIES ${IDYN_LIBRARIES} ${YARP_LIBRARIES})

  ENDIF(NESTED_BUILD)
  MESSAGE(STATUS "IDYN: ???")

  IF(IDYN_INCLUDE_DIRS AND IDYN_LIBRARIES)
    SET(IDYN_FOUND TRUE)
  ELSE(IDYN_INCLUDE_DIRS AND IDYN_LIBRARIES)
    SET(IDYN_FOUND FALSE)
  ENDIF(IDYN_INCLUDE_DIRS AND IDYN_LIBRARIES)

  SET(IDYN_FOUND TRUE)
ELSE(NOT IDYN_FOUND)
  MESSAGE(STATUS "iDyn found")
ENDIF(NOT IDYN_FOUND)
