
MESSAGE(STATUS "ICUBQWIDGETS Library")

IF (NESTED_BUILD)
  SET(ICUBQWIDGETS_LIBRARIES libICUB_QWidgets)
ELSE (NESTED_BUILD)
  FIND_LIBRARY(ICUBQWIDGETS_LIBRARIES libICUB_QWidgets ${ICUBQWIDGETS_DIR})
ENDIF (NESTED_BUILD)

SET(ICUBQWIDGETS_INCLUDE_DIRS ${ICUBQWIDGETS_DIR} ${ICUBQWIDGETS_DIR}/include)

