#!/bin/sh

# Copyright (C) 2007 Jonas Ruesch
# CopyPolicy: Released under the terms of the GNU GPL v2.0.
# *** Configuration ***
# Robot Name
NAME_ROBOT=chico

# Robot Ports
NAME_SOURCE_IMAGE_RIGHTEYE=/RightEye
NAME_SOURCE_IMAGE_LEFTEYE=/LeftEye
NAME_CONTROLBOARD=/esdboard
NAME_SOURCE_SOUND=/sound_grabber

# Paths
EXECUTABLE_PATH=$ICUB_DIR/bin
CONFIGURATION_PATH=$ICUB_DIR/conf

# Module: Camera Calibration Right Eye
CAMCALIB_RIGHT_EXECUTABLE=camCalib
CAMCALIB_RIGHT_CONFIG_FILE=chica_eyes.ini
CAMCALIB_RIGHT_CONFIG_GROUP=CAMERA_CALIBRATION_RIGHT
CAMCALIB_RIGHT_NAME=/$NAME_ROBOT/camcalib/right
CAMCALIB_RIGHT_PORT_IMAGE=$CAMCALIB_RIGHT_NAME/image

# Module: Camera Calibration Left Eye
CAMCALIB_LEFT_EXECUTABLE=camCalib
CAMCALIB_LEFT_CONFIG_FILE=chica_eyes.ini
CAMCALIB_LEFT_CONFIG_GROUP=CAMERA_CALIBRATION_LEFT
CAMCALIB_LEFT_NAME=/$NAME_ROBOT/camcalib/left
CAMCALIB_LEFT_PORT_IMAGE=$CAMCALIB_LEFT_NAME/image


# Module: Salience Right Eye
SALIENCE_RIGHT_EXECUTABLE=salience
SALIENCE_RIGHT_CONFIG_FILE=chica_salience.ini
SALIENCE_RIGHT_CONFIG_GROUP=none
SALIENCE_RIGHT_NAME=/$NAME_ROBOT/salience/right
SALIENCE_RIGHT_PORT_VIEW=$SALIENCE_RIGHT_NAME/view
SALIENCE_RIGHT_PORT_MAP=$SALIENCE_RIGHT_NAME/map

# Module: Salience Left Eye
SALIENCE_LEFT_EXECUTABLE=salience
SALIENCE_LEFT_CONFIG_FILE=chica_salience.ini
SALIENCE_LEFT_CONFIG_GROUP=none
SALIENCE_LEFT_NAME=/$NAME_ROBOT/salience/left
SALIENCE_LEFT_PORT_VIEW=$SALIENCE_LEFT_NAME/view
SALIENCE_LEFT_PORT_MAP=$SALIENCE_LEFT_NAME/map

# Module: ControlGaze
CONTROLGAZE_EXECUTABLE=controlGaze
CONTROLGAZE_CONFIG_FILE=chicx_control.ini
CONTROLGAZE_CONFIG_GROUP=CONTROLGAZE
CONTROLGAZE_NAME=/$NAME_ROBOT/controlGaze
CONTROLGAZE_PORT_CONTROLBOARD=$CONTROLGAZE_NAME/controlboard
CONTROLGAZE_PORT_DIS=$CONTROLGAZE_NAME/dis
CONTROLGAZE_PORT_EGOSPHERE_CONF=$CONTROLGAZE_NAME/egosphere/conf
CONTROLGAZE_PORT_IMU=$CONTROLGAZE_NAME/imu
CONTROLGAZE_PORT_POS=$CONTROLGAZE_NAME/pos
CONTROLGAZE_PORT_POSSIBLEDIRECTIONS=$CONTROLGAZE_NAME/possibledirections/vec:o
CONTROLGAZE_PORT_TRACKERSIGNAL=$CONTROLGAZE_NAME/trackersignal/bot:o
CONTROLGAZE_PORT_VEL=$CONTROLGAZE_NAME/vel


# Module: Face Detector
FACEDETECT_EXECUTABLE=faceEyeDetector
FACEDETECT_CONFIG_FILE=opencvFaceDetector.ini
FACEDETECT_CONFIG_GROUP=none
FACEDETECT_NAME=/$NAME_ROBOT/facedetector
FACEDETECT_PORT_OUT=$FACEDETECT_NAME/out
FACEDETECT_PORT_DETECT=$FACEDETECT_NAME/detectOut
FACEDETECT_PORT_IN=$FACEDETECT_NAME/rgb


# Module: Histogram Tracker
HISTTRACKER_EXECUTABLE=histTracker
HISTTRACKER_CONFIGFILE=histTracker.ini
HISTTRACKER_CONFIGGROUP=none
HISTTRACKER_NAME=/$NAME_ROBOT/histtracker
HISTTRACKER_PORT_IN=$HISTTRACKER_NAME/rgb
HISTTRACKER_PORT_DETECT=$HISTTRACKER_NAME/detectIn
HISTTRACKER_PORT_OUT=$HISTTRACKER_NAME/out
HISTTRACKER_PORT_TRACK=$HISTTRACKER_NAME/normOut


# Viewer CamCalib
VIEWER_CAMCALIB_LEFT_EXECUTABLE=yarpview
VIEWER_CAMCALIB_LEFT_PORT=/view/camCalib/right
VIEWER_CAMCALIB_LEFT_REFRESHTIME=75
VIEWER_CAMCALIB_LEFT_POSX=20
VIEWER_CAMCALIB_LEFT_POSY=20
#VIEWER_CAMCALIB_LEFT_CLICK=$VIEWER_CAMCALIB_RIGHT_PORT/click

# Viewer Face Detector
VIEWER_FACEDETECT_EXECUTABLE=yarpview
VIEWER_FACEDETECT_PORT=/view/facedetect
VIEWER_FACEDETECT_REFRESHTIME=75
VIEWER_FACEDETECT_POSX=100
VIEWER_FACEDETECT_POSY=200
#VIEWER_FACEDETECT_CLICK=$VIEWER_FACEDETECT_PORT/click

# Viewer Histogram Tracker
VIEWER_HISTTRACKER_EXECUTABLE=yarpview
VIEWER_HISTTRACKER_PORT=/view/histtrack
VIEWER_HISTTRACKER_REFRESHTIME=75
VIEWER_HISTTRACKER_POSX=300
VIEWER_HISTTRACKER_POSY=200
#VIEWER_HISTTRACKER_CLICK=$VIEWER_HISTTRACKER_PORT/click

