#!/bin/bash

source ./config.sh

$EXECUTABLE_PATH/$CONTROLGAZE_EXECUTABLE --name $CONTROLGAZE_NAME --file $CONFIGURATION_PATH/$CONTROLGAZE_CONFIG_FILE --group $CONTROLGAZE_CONFIG_GROUP --remoteEgoSphere $NAME_ROBOT/$EGOSPHERE_PORT_CONF --motorboard $NAME_CONTROLBOARD
