#!/bin/bash

source ./config.sh

# viewer camCalib left
$VIEWER_CAMCALIB_LEFT_EXECUTABLE --name $VIEWER_CAMCALIB_LEFT_PORT --RefreshTime $VIEWER_CAMCALIB_LEFT_REFRESHTIME --out $VIEWER_CAMCALIB_LEFT_CLICK --PosX $VIEWER_CAMCALIB_RIGHT_POSX --PosY $VIEWER_CAMCALIB_RIGHT_POSY &

# viewer face detector
$VIEWER_FACEDETECT_EXECUTABLE --name $VIEWER_FACEDETECT_PORT --RefreshTime $VIEWER_FACEDETECT_REFRESHTIME --out $VIEWER_FACEDETECT_CLICK --PosX $VIEWER_FACEDETECT_POSX --PosY $VIEWER_FACEDETECT_POSY &

# viewer histogram tracker
$VIEWER_HISTTRACKER_EXECUTABLE --name $VIEWER_HISTTRACKER_PORT --RefreshTime $VIEWER_HISTTRACKER_REFRESHTIME --out $VIEWER_HISTTRACKER_CLICK --PosX $VIEWER_HISTTRACKER_POSX --PosY $VIEWER_HISTTRACKER_POSY &

